<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>Assets\OzzTradeDigest-256.ico</ApplicationIcon>
		<RootNamespace>TD.WPF</RootNamespace>

		<Version>0.2.3</Version>
		<AssemblyVersion>0.2.3.0</AssemblyVersion>
		<FileVersion>0.2.3.0</FileVersion>
		<InformationalVersion>0.2.3</InformationalVersion>

		<Company>Özalp Döndüren</Company>
		<Product>Ozz Trade Digest</Product>
		<Description>Trade Journaling and Flow Control Application by Özalp Döndüren</Description>
		<Copyright>Copyright © 2026</Copyright>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Assets\OzzTradeDigest-256.ico" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\OzzTradeDigest.AppInfra\OzzTradeDigest.AppInfra.csproj" />
		<ProjectReference Include="..\OzzTradeDigest.i18n\OzzTradeDigest.i18n.csproj" />
		<ProjectReference Include="..\OzzTradeDigest\OzzTradeDigest.csproj" />
		<ProjectReference Include="..\OzzTradeDigest.SQLite\OzzTradeDigest.SQLite.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
	</ItemGroup>

</Project>
