Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (1, 'USD', 'US Dollar', 100, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (2, 'USDT', 'Tether', 250, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (3, 'USDC', 'USD Coin', 250, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (4, 'AUD', 'Australian Dollar', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (5, 'BTC', 'Bitcoin', 300, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (6, 'CAD', 'Canadian Dollar', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (7, 'CHF', 'Swiss Franc', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (8, 'ETH', 'Ethereum', 400, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (9, 'EUR', 'Euro', 200, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (10, 'GBP', 'Pound Sterling', 200, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (11, 'HKD', 'Hong Kong Dollar', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (12, 'INR', 'Indian Rupee', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (13, 'JPY', 'Japanese Yen', 200, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (14, 'KRW', 'South Korean Won', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (15, 'MYR', 'Malaysian Ringgit', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (16, 'NOK', 'Norwegian Krone', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (17, 'NZD', 'New Zealand Dollar', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (18, 'RUB', 'Russian Ruble', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (19, 'SEK', 'Swedish Krona', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (20, 'SGD', 'Singapore Dollar', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (21, 'TRY', 'Turkish Lira', 1000, 1);
Insert into Currencies(Id, CurrencyTicker, Description, DisplayOrder, IsActive) values (22, 'ZAR', 'South African Rand', 1000, 1);
