//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using TD.Models;
using TD.RepositoryContracts;
using TD.SQLite.Extensions;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for Currency CRUD operations.
    /// </summary>
    public partial class CurrencyRepository : AbstractDatabaseRepository<Currency>, ICurrencyRepository
    {
        public CurrencyRepository(string databasePath) : base(databasePath, "Currencies")
        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            _databasePath = databasePath;

            InitializeDatabase();
            OnInitialized();
        }
        private readonly string _databasePath;
        private readonly string _selectStatement;

        protected IExchangeRepository ExchangeRepository
        {
            get
            {
                if (_exchangeRepository == null)
                {
                    _exchangeRepository = new ExchangeRepository(_databasePath, currencyRepository: this);
                }
                return _exchangeRepository;
            }
        }
        private IExchangeRepository? _exchangeRepository;

        protected ISymbolRepository SymbolRepository
        {
            get
            {
                if (_symbolRepository == null)
                {
                    _symbolRepository = new SymbolRepository(_databasePath, currencyRepository: this);
                }
                return _symbolRepository;
            }
        }
        private ISymbolRepository? _symbolRepository;


        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "Currency.sql");
            SeedIfEmpty(connection, "Currencies-Data.sql");
        }

        partial void OnInitialized();

        public async Task<IReadOnlyList<Currency>> GetAllAsync(bool? isActive = null)
        {
            var result = new List<Currency>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            if (isActive.HasValue)
            {
                command.CommandText += " WHERE IsActive = @isActive";
                command.AddParameter("@isActive", isActive.Value);
            }

            command.CommandText += " ORDER BY DisplayOrder, CurrencyTicker";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var currency = MapCurrency(reader);
                result.Add(currency);
            }

            return result;
        }

        public async Task<Currency?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var currency = MapCurrency(reader);

            OnLoaded(currency);
            return currency;
        }

        public async Task<Currency?> GetByCurrencyTickerAsync(string? currencyTicker)
        {
            if (string.IsNullOrWhiteSpace(currencyTicker))
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE CurrencyTicker = @currencyTicker";
            command.Parameters.AddWithValue("@currencyTicker", currencyTicker);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var currency = MapCurrency(reader);

            OnLoaded(currency);
            return currency;
        }
        partial void OnLoaded(Currency currency);

        public async Task<int> CreateAsync(Currency currency)
        {
            ArgumentNullException.ThrowIfNull(currency);
            ValidateOrThrow(currency);

            await using var connection = await GetOpenConnectionAsync();
            var existingCurrency = await GetByCurrencyTickerAsync(currency.CurrencyTicker);
            if (existingCurrency != null)
            {
                currency.Id = existingCurrency.Id;
                await UpdateAsync(currency);
                return existingCurrency.Id;
            }

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@currencyTicker, @description, @displayOrder, @isActive);
            SELECT last_insert_rowid();";

            command.AddParameter("@currencyTicker", currency.CurrencyTicker);
            command.AddNullableParameter("@description", currency.Description);
            command.AddParameter("@displayOrder", currency.DisplayOrder);
            command.AddParameter("@isActive", currency.IsActive);

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));

            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            currency.Id = id;
            OnCreated(currency);

            return id;
        }
        partial void OnCreated(Currency currency);

        /// <summary>
        /// Determines whether a currency can be safely deleted based on the absence of related records.
        /// </summary>
        /// <remarks>A currency can be deleted only if there are no associated records. Use this method
        /// before attempting to delete a currency to avoid violating referential integrity.</remarks>
        /// <param name="id">The identifier of the currency record to check for deletability.</param>
        /// <returns>A task that represents the asynchronous operation. The task result is <see langword="true"/> if the currency
        /// can be deleted; otherwise, <see langword="false"/>.</returns>
        public async Task<bool> CanDeleteAsync(int id)
        {
            if (id < 1)
                return false;

            bool result = true;

            // Checking any exchange record exists through Exchange.DefaultCurrencyId reference
            result = result && !(await ExchangeRepository.AnyByDefaultCurrencyIdAsync(id));

            // Checking any symbol record exists through Symbol.PriceCurrencyId reference
            result = result && !(await SymbolRepository.AnyByPriceCurrencyIdAsync(id));

            return result;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(Currency currency)
        {
            ArgumentNullException.ThrowIfNull(currency);
            ValidateOrThrow(currency);

            await using var connection = await GetOpenConnectionAsync();
            var existingCurrency = await GetByCurrencyTickerAsync(currency.CurrencyTicker);
            if (existingCurrency != null && existingCurrency.Id != currency.Id)
            {
                throw new InvalidOperationException($"A different Currency with the same CurrencyTicker already exists: {currency.CurrencyTicker}");
            }

            existingCurrency = await GetByIdAsync(currency.Id);
            bool noChanges = existingCurrency != null
                          && existingCurrency.Description == currency.Description
                          && existingCurrency.DisplayOrder == currency.DisplayOrder
                          && existingCurrency.IsActive == currency.IsActive;

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // CurrencyTicker is not updated to avoid complications with existing references,
            // so only Description, DisplayOrder, IsActive are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                Description = @description,
                DisplayOrder = @displayOrder,
                IsActive = @isActive
            WHERE Id = @id";

            command.AddParameter("@id", currency.Id);
            command.AddNullableParameter("@description", currency.Description);
            command.AddParameter("@displayOrder", currency.DisplayOrder);
            command.AddParameter("@isActive", currency.IsActive);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(currency);
            }

            return affectedRows > 0;
        }
        partial void OnUpdated(Currency currency);

        private static Currency MapCurrency(SqliteDataReader reader)
        {
            var currency = new Currency
            {
                Id = reader.GetInt32(ColNrs.Id),
                CurrencyTicker = reader.GetString(ColNrs.CurrencyTicker),
                Description = reader.IsDBNull(ColNrs.Description) ? null
                            : reader.GetString(ColNrs.Description),
                DisplayOrder = reader.GetInt32(ColNrs.DisplayOrder),
                IsActive = reader.GetInt64(ColNrs.IsActive) == 1
            };

            return currency;
        }

        /// <summary>
        /// Contains the column numbers for each property in the SQLiteDataReader.
        /// </summary>
        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int CurrencyTicker = 1;
            public readonly static int Description = 2;
            public readonly static int DisplayOrder = 3;
            public readonly static int IsActive = 4;
        }

        /// <summary>
        /// Contains the names of all columns in the SQLiteDataReader.
        /// </summary>
        public readonly string[] ColumnNames = new[] {
            "Id",
            "CurrencyTicker",
            "Description",
            "DisplayOrder",
            "IsActive"
        };
    }
}
