//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using TD.Models;
using TD.RepositoryContracts;
using TD.SQLite.Extensions;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for ExitOrder CRUD operations.
    /// </summary>
    public partial class ExitOrderRepository : AbstractDatabaseRepository<ExitOrder>, IExitOrderRepository
    {
        public ExitOrderRepository(string databasePath) : base(databasePath, "ExitOrders")
        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            _databasePath = databasePath;

            InitializeDatabase();
            OnInitialized();
        }
        private readonly string _databasePath;
        private readonly string _selectStatement;


        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "ExitOrder.sql");
        }

        partial void OnInitialized();

        public async Task<IReadOnlyList<ExitOrder>> GetAllAsync()
        {
            var result = new List<ExitOrder>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " ORDER BY UpdatedAt DESC, Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var exitOrder = MapExitOrder(reader);
                result.Add(exitOrder);
            }

            return result;
        }

        public async Task<bool> AnyByTradeIdAsync(int tradeId)
        {
            if (tradeId < 1)
                return false;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"SELECT COUNT(1) FROM {_tableName} WHERE TradeId = @tradeId";
            command.Parameters.AddWithValue("@tradeId", tradeId);
            var result = await command.ExecuteScalarAsync();
            return Convert.ToInt64(result) > 0;
        }


        public async Task<IReadOnlyList<ExitOrder>> GetByTradeIdAsync(int tradeId)
        {
            var result = new List<ExitOrder>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE TradeId = @tradeId";
            command.AddParameter("@tradeId", tradeId);
            command.CommandText += " ORDER BY UpdatedAt DESC, Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var exitOrder = MapExitOrder(reader);
                result.Add(exitOrder);
            }

            return result;
        }


        public async Task<ExitOrder?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var exitOrder = MapExitOrder(reader);

            OnLoaded(exitOrder);
            return exitOrder;
        }
        partial void OnLoaded(ExitOrder exitOrder);

        public async Task<int> CreateAsync(ExitOrder exitOrder)
        {
            ArgumentNullException.ThrowIfNull(exitOrder);
            ValidateOrThrow(exitOrder);

            await using var connection = await GetOpenConnectionAsync();

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@tradeId, @orderType, @orderPrice, @filledPrice, @orderQuantity, @filledQuantity,
                    @orderValue, @filledValue, @notes, @cancellationTime, @filledTime, @updatedAt);
            SELECT last_insert_rowid();";

            command.AddParameter("@tradeId", exitOrder.TradeId);
            command.AddParameter("@orderType", (int)exitOrder.OrderType);
            command.AddDecimalToTextParameter("@orderPrice", exitOrder.OrderPrice);
            command.AddDecimalToTextParameter("@filledPrice", exitOrder.FilledPrice);
            command.AddDecimalToTextParameter("@orderQuantity", exitOrder.OrderQuantity);
            command.AddDecimalToTextParameter("@filledQuantity", exitOrder.FilledQuantity);
            command.AddDecimalToIntegerParameter("@orderValue",
                                                exitOrder.OrderValue,
                                                DecimalToIntegerScale.OrderValue);
            command.AddDecimalToIntegerParameter("@filledValue",
                                                exitOrder.FilledValue,
                                                DecimalToIntegerScale.FilledValue);
            command.AddNullableParameter("@notes", exitOrder.Notes);
            command.AddDateTimeToTextParameter("@cancellationTime", exitOrder.CancellationTime);
            command.AddDateTimeToTextParameter("@filledTime", exitOrder.FilledTime);
            command.AddDateTimeToTextParameter("@updatedAt", DateTime.Now);

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));

            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            exitOrder.Id = id;
            OnCreated(exitOrder);

            return id;
        }
        partial void OnCreated(ExitOrder exitOrder);

        /// <summary>
        /// Determines whether a exitOrder can be safely deleted based on the absence of related records.
        /// </summary>
        /// <remarks>A exitOrder can be deleted only if there are no associated records. Use this method
        /// before attempting to delete a exitOrder to avoid violating referential integrity.</remarks>
        /// <param name="id">The identifier of the exitOrder record to check for deletability.</param>
        /// <returns>A task that represents the asynchronous operation. The task result is <see langword="true"/> if the exitOrder
        /// can be deleted; otherwise, <see langword="false"/>.</returns>
        public Task<bool> CanDeleteAsync(int id)
        {
            if (id < 1)
                return Task.FromResult(false);

            return Task.FromResult(true);
        }

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(ExitOrder exitOrder)
        {
            ArgumentNullException.ThrowIfNull(exitOrder);
            ValidateOrThrow(exitOrder);

            await using var connection = await GetOpenConnectionAsync();
            var existingExitOrder = await GetByIdAsync(exitOrder.Id);
            bool noChanges = existingExitOrder != null
                          && existingExitOrder.OrderType == exitOrder.OrderType
                          && existingExitOrder.OrderPrice == exitOrder.OrderPrice
                          && existingExitOrder.FilledPrice == exitOrder.FilledPrice
                          && existingExitOrder.OrderQuantity == exitOrder.OrderQuantity
                          && existingExitOrder.FilledQuantity == exitOrder.FilledQuantity
                          && existingExitOrder.OrderValue == exitOrder.OrderValue
                          && existingExitOrder.FilledValue == exitOrder.FilledValue
                          && existingExitOrder.Notes == exitOrder.Notes
                          && existingExitOrder.FilledTime == exitOrder.FilledTime
                          && existingExitOrder.UpdatedAt == exitOrder.UpdatedAt;

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // TradeId, CancellationTime are not updated to avoid complications with existing references,
            // so only OrderType, OrderPrice, FilledPrice, OrderQuantity, FilledQuantity, OrderValue, FilledValue, Notes, FilledTime, UpdatedAt are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                OrderType = @orderType,
                OrderPrice = @orderPrice,
                FilledPrice = @filledPrice,
                OrderQuantity = @orderQuantity,
                FilledQuantity = @filledQuantity,
                OrderValue = @orderValue,
                FilledValue = @filledValue,
                Notes = @notes,
                FilledTime = @filledTime,
                UpdatedAt = @updatedAt
            WHERE Id = @id";

            command.AddParameter("@id", exitOrder.Id);
            command.AddParameter("@orderType", (int)exitOrder.OrderType);
            command.AddDecimalToTextParameter("@orderPrice", exitOrder.OrderPrice);
            command.AddDecimalToTextParameter("@filledPrice", exitOrder.FilledPrice);
            command.AddDecimalToTextParameter("@orderQuantity", exitOrder.OrderQuantity);
            command.AddDecimalToTextParameter("@filledQuantity", exitOrder.FilledQuantity);
            command.AddDecimalToIntegerParameter("@orderValue",
                                                exitOrder.OrderValue,
                                                DecimalToIntegerScale.OrderValue);
            command.AddDecimalToIntegerParameter("@filledValue",
                                                exitOrder.FilledValue,
                                                DecimalToIntegerScale.FilledValue);
            command.AddNullableParameter("@notes", exitOrder.Notes);
            command.AddDateTimeToTextParameter("@filledTime", exitOrder.FilledTime);
            command.AddDateTimeToTextParameter("@updatedAt", DateTime.Now);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(exitOrder);
            }

            return affectedRows > 0;
        }
        partial void OnUpdated(ExitOrder exitOrder);
        partial void OnUpdated(int exitOrderId);

        public async Task<bool> UpdateCancellationTimeAsync(int id, DateTime cancellationTime)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = @$"UPDATE {_tableName} SET
                CancellationTime = @cancellationTime,                UpdatedAt = @updatedAt            WHERE Id = @id";

            command.AddParameter("@id", id);
            command.AddDateTimeToTextParameter("@cancellationTime", cancellationTime);
            command.AddDateTimeToTextParameter("@updatedAt", DateTime.Now);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(id);
            }

            return affectedRows > 0;
        }

        private static ExitOrder MapExitOrder(SqliteDataReader reader)
        {
            var exitOrder = new ExitOrder
            {
                Id = reader.GetInt32(ColNrs.Id),
                TradeId = reader.GetInt32(ColNrs.TradeId),
                OrderType = (ExitOrderType)reader.GetInt32(ColNrs.OrderType),
                OrderPrice = reader.GetDecimalFromText(ColNrs.OrderPrice) ?? 0m,
                FilledPrice = reader.IsDBNull(ColNrs.FilledPrice) ? null
                            : reader.GetDecimalFromText(ColNrs.FilledPrice),
                OrderQuantity = reader.IsDBNull(ColNrs.OrderQuantity) ? null
                              : reader.GetDecimalFromText(ColNrs.OrderQuantity),
                FilledQuantity = reader.IsDBNull(ColNrs.FilledQuantity) ? null
                               : reader.GetDecimalFromText(ColNrs.FilledQuantity),
                OrderValue = reader.IsDBNull(ColNrs.OrderValue) ? null
                           : reader.GetDecimalFromInteger(ColNrs.OrderValue,
                                           DecimalToIntegerScale.OrderValue),
                FilledValue = reader.IsDBNull(ColNrs.FilledValue) ? null
                            : reader.GetDecimalFromInteger(ColNrs.FilledValue,
                                            DecimalToIntegerScale.FilledValue),
                Notes = reader.IsDBNull(ColNrs.Notes) ? null
                      : reader.GetString(ColNrs.Notes),
                CancellationTime = reader.IsDBNull(ColNrs.CancellationTime) ? null
                                 : ToLocalDateTime(reader.GetString(ColNrs.CancellationTime)),
                FilledTime = reader.IsDBNull(ColNrs.FilledTime) ? null
                           : ToLocalDateTime(reader.GetString(ColNrs.FilledTime)),
                UpdatedAt = ToLocalDateTime(reader.GetString(ColNrs.UpdatedAt)) ?? DateTime.MinValue
            };

            return exitOrder;
        }

        /// <summary>
        /// Contains the column numbers for each property in the SQLiteDataReader.
        /// </summary>
        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int TradeId = 1;
            public readonly static int OrderType = 2;
            public readonly static int OrderPrice = 3;
            public readonly static int FilledPrice = 4;
            public readonly static int OrderQuantity = 5;
            public readonly static int FilledQuantity = 6;
            public readonly static int OrderValue = 7;
            public readonly static int FilledValue = 8;
            public readonly static int Notes = 9;
            public readonly static int CancellationTime = 10;
            public readonly static int FilledTime = 11;
            public readonly static int UpdatedAt = 12;
        }

        /// <summary>
        /// Contains the names of all columns in the SQLiteDataReader.
        /// </summary>
        public readonly string[] ColumnNames = new[] {
            "Id",
            "TradeId",
            "OrderType",
            "OrderPrice",
            "FilledPrice",
            "OrderQuantity",
            "FilledQuantity",
            "OrderValue",
            "FilledValue",
            "Notes",
            "CancellationTime",
            "FilledTime",
            "UpdatedAt"
        };

        /// <summary>
        /// Contains the scale values used for converting decimal properties to integer storage.
        /// </summary>
        public readonly struct DecimalToIntegerScale
        {
            public readonly static int OrderPrice = 0;
            public readonly static int FilledPrice = 0;
            public readonly static int OrderQuantity = 0;
            public readonly static int FilledQuantity = 0;
            public readonly static int OrderValue = 4;
            public readonly static int FilledValue = 4;
        }
    }
}
