//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using System.Globalization;
using Microsoft.Data.Sqlite;

namespace TD.SQLite
{
    /// <summary>
    /// Provides access to database metadata, including tracking and updating the last modification time for the SQLite
    /// database. Implements a singleton pattern to ensure a single instance per database path.
    /// </summary>
    /// <remarks>This repository is responsible for managing the 'DatabaseMetadata' table, which stores the
    /// last update timestamp for the database. The singleton instance is created with the specified database path and
    /// reused for subsequent calls. This class is thread-safe for read operations, but callers should ensure thread
    /// safety when using the same instance for concurrent write operations. Use this repository to retrieve or update
    /// the last modification time, which is useful for cache invalidation, synchronization, or backup scenarios.</remarks>
	public partial class MetadataRepository : IMetadataRepository
    {
        /// <summary>
        /// Initializes a new instance with the specified database path.
        /// </summary>
        /// <param name="databasePath">The full path to the SQLite database file.</param>
        private MetadataRepository(string databasePath)
        {
            _connectionString = $"Data Source={databasePath}";
            InitializeDatabase();
        }

        /// <summary>
        /// <see langword="public"/> <see langword="static"/> method to get the singleton instance of MetadataRepository.
        /// </summary>
        /// <param name="databasePath">The full path to the SQLite database file.</param>
        /// <returns>The singleton instance of MetadataRepository.</returns>
        public static MetadataRepository GetInstance(string databasePath)
        {
            if (_instance == null)
            {
                _instance = new MetadataRepository(databasePath);
            }
            return _instance;
        }
        private static MetadataRepository? _instance;

        public string ConnectionString { get { return _connectionString; } }
        private readonly string _connectionString;

        private void InitializeDatabase()
        {
            using var connection = new SqliteConnection(_connectionString);
            connection.Open();

            var metadataCommand = connection.CreateCommand();
            metadataCommand.CommandText = @"
                    CREATE TABLE IF NOT EXISTS DatabaseMetadata (
                        Id INTEGER PRIMARY KEY CHECK (Id = 1),
                        LastUpdateUtc TEXT NULL
                    );

                    INSERT INTO DatabaseMetadata (Id, LastUpdateUtc)
                    VALUES (1, @lastUpdateUtc)
                    ON CONFLICT(Id) DO NOTHING;";
            metadataCommand.Parameters.AddWithValue("@lastUpdateUtc", string.Empty);
            metadataCommand.ExecuteNonQuery();

            var readMetadataCommand = connection.CreateCommand();
            readMetadataCommand.CommandText = "SELECT LastUpdateUtc FROM DatabaseMetadata WHERE Id = 1";
            var lastUpdateUtc = readMetadataCommand.ExecuteScalar() as string;
            LastUpdateTime = ToLocalDateTime(lastUpdateUtc);
        }

        /// <summary>
        /// Gets the last data update time in local time.
        /// </summary>
        public DateTime? LastUpdateTime { get; private set; }

        /// <summary>
        /// Gets the last database update time in UTC.
        /// </summary>
        /// <returns>The last update time, or null if never updated.</returns>
        public async Task<DateTime?> GetLastUpdateTimeUtcAsync()
        {
            using var connection = new SqliteConnection(_connectionString);
            await connection.OpenAsync();

            var command = connection.CreateCommand();
            command.CommandText = "SELECT LastUpdateUtc FROM DatabaseMetadata WHERE Id = 1";

            var result = await command.ExecuteScalarAsync() as string;

            if (string.IsNullOrWhiteSpace(result))
            {
                return null;
            }

            if (DateTime.TryParse(result, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal, out var utcTime))
            {
                return utcTime;
            }

            return null;
        }

        /// <summary>
        /// Saves the current UTC time as the last database update time.
        /// </summary>
        /// <param name="connection">The SQLite connection to use for the update.</param>
        /// <returns>A task representing the asynchronous operation.</returns>
        public async Task SaveLastUpdateUtcAsync(SqliteConnection connection)
        {
            var nowUtc = DateTimeOffset.UtcNow;

            var metadataCommand = connection.CreateCommand();
            metadataCommand.CommandText = @"
                    UPDATE DatabaseMetadata
                    SET LastUpdateUtc = @lastUpdateUtc
                    WHERE Id = 1";
            metadataCommand.Parameters.AddWithValue("@lastUpdateUtc", nowUtc.ToString("O"));

            await metadataCommand.ExecuteNonQueryAsync();
            LastUpdateTime = nowUtc.ToLocalTime().DateTime;
        }

        /// <summary>
        /// Gets the last database update time in local time.
        /// </summary>
        /// <returns>The last update time in local time, or null if never updated.</returns>
        public async Task<DateTime?> GetLastUpdateTimeAsync()
        {
            var utcTime = await GetLastUpdateTimeUtcAsync();
            return utcTime?.ToLocalTime();
        }

        private static DateTime? ToLocalDateTime(string? utcValue)
        {
            DateTime? dateTime = null;
            if (DateTimeOffset.TryParse(utcValue, out var parsedUtc))
                dateTime = parsedUtc.ToLocalTime().DateTime;

            return dateTime;
        }
    }

    /// <summary>
    /// Repository interface for accessing database metadata.
    /// </summary>
    public interface IMetadataRepository
    {
        /// <summary>
        /// Gets the last database update time in UTC.
        /// </summary>
        /// <returns>The last update time, or null if never updated.</returns>
        Task<DateTime?> GetLastUpdateTimeUtcAsync();

        /// <summary>
        /// Gets the last database update time in local time.
        /// </summary>
        /// <returns>The last update time in local time, or null if never updated.</returns>
        Task<DateTime?> GetLastUpdateTimeAsync();

        /// <summary>
        /// Saves the current UTC time as the last database update time.
        /// </summary>
        /// <param name="connection">The SQLite connection to use for the update.</param>
        /// <returns>A task representing the asynchronous operation.</returns>
        Task SaveLastUpdateUtcAsync(SqliteConnection connection);
    }
}