//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using TD.Models;
using TD.RepositoryContracts;
using TD.SQLite.Extensions;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for Session CRUD operations.
    /// </summary>
    public partial class SessionRepository : AbstractDatabaseRepository<Session>, ISessionRepository
    {
        public SessionRepository(string databasePath) : base(databasePath, "Sessions")
        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            _databasePath = databasePath;

            InitializeDatabase();
            OnInitialized();
        }
        private readonly string _databasePath;
        private readonly string _selectStatement;


        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "Session.sql");
            SeedIfEmpty(connection, "Sessions-Data.sql");
        }

        partial void OnInitialized();

        public async Task<IReadOnlyList<Session>> GetAllAsync()
        {
            var result = new List<Session>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " ORDER BY DisplayOrder, Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var session = MapSession(reader);
                result.Add(session);
            }

            return result;
        }

        public async Task<bool> AnyByExchangeIdAsync(int exchangeId)
        {
            if (exchangeId < 1)
                return false;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"SELECT COUNT(1) FROM {_tableName} WHERE ExchangeId = @exchangeId";
            command.Parameters.AddWithValue("@exchangeId", exchangeId);
            var result = await command.ExecuteScalarAsync();
            return Convert.ToInt64(result) > 0;
        }


        public async Task<IReadOnlyList<Session>> GetByExchangeIdAsync(int exchangeId)
        {
            var result = new List<Session>();

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE ExchangeId = @exchangeId";
            command.AddParameter("@exchangeId", exchangeId);
            command.CommandText += " ORDER BY DisplayOrder, Id";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var session = MapSession(reader);
                result.Add(session);
            }

            return result;
        }


        public async Task<Session?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var session = MapSession(reader);

            OnLoaded(session);
            return session;
        }
        partial void OnLoaded(Session session);

        public async Task<int> CreateAsync(Session session)
        {
            ArgumentNullException.ThrowIfNull(session);
            ValidateOrThrow(session);

            await using var connection = await GetOpenConnectionAsync();

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@exchangeId, @sessionType, @dayOfWeek, @localOpen, @localClose);
            SELECT last_insert_rowid();";

            command.AddParameter("@exchangeId", session.ExchangeId);
            command.AddParameter("@sessionType", (int)session.SessionType);
            command.AddParameter("@dayOfWeek", session.DayOfWeek);
            command.AddParameter("@localOpen", session.LocalOpen);
            command.AddParameter("@localClose", session.LocalClose);

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));

            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            session.Id = id;
            OnCreated(session);

            return id;
        }
        partial void OnCreated(Session session);

        /// <summary>
        /// Determines whether a session can be safely deleted based on the absence of related records.
        /// </summary>
        /// <remarks>A session can be deleted only if there are no associated records. Use this method
        /// before attempting to delete a session to avoid violating referential integrity.</remarks>
        /// <param name="id">The identifier of the session record to check for deletability.</param>
        /// <returns>A task that represents the asynchronous operation. The task result is <see langword="true"/> if the session
        /// can be deleted; otherwise, <see langword="false"/>.</returns>
        public Task<bool> CanDeleteAsync(int id)
        {
            if (id < 1)
                return Task.FromResult(false);

            return Task.FromResult(true);
        }

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(Session session)
        {
            ArgumentNullException.ThrowIfNull(session);
            ValidateOrThrow(session);

            await using var connection = await GetOpenConnectionAsync();
            var existingSession = await GetByIdAsync(session.Id);
            bool noChanges = existingSession != null
                          && existingSession.SessionType == session.SessionType
                          && existingSession.DayOfWeek == session.DayOfWeek
                          && existingSession.LocalOpen == session.LocalOpen
                          && existingSession.LocalClose == session.LocalClose;

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // ExchangeId is not updated to avoid complications with existing references,
            // so only SessionType, DayOfWeek, LocalOpen, LocalClose are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                SessionType = @sessionType,
                DayOfWeek = @dayOfWeek,
                LocalOpen = @localOpen,
                LocalClose = @localClose
            WHERE Id = @id";

            command.AddParameter("@id", session.Id);
            command.AddParameter("@sessionType", (int)session.SessionType);
            command.AddParameter("@dayOfWeek", session.DayOfWeek);
            command.AddParameter("@localOpen", session.LocalOpen);
            command.AddParameter("@localClose", session.LocalClose);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(session);
            }

            return affectedRows > 0;
        }
        partial void OnUpdated(Session session);

        private static Session MapSession(SqliteDataReader reader)
        {
            var session = new Session
            {
                Id = reader.GetInt32(ColNrs.Id),
                ExchangeId = reader.GetInt32(ColNrs.ExchangeId),
                SessionType = (SessionType)reader.GetInt32(ColNrs.SessionType),
                DayOfWeek = reader.IsDBNull(ColNrs.DayOfWeek) ? null
                          : reader.GetInt32(ColNrs.DayOfWeek),
                LocalOpen = reader.GetString(ColNrs.LocalOpen),
                LocalClose = reader.GetString(ColNrs.LocalClose)
            };

            return session;
        }

        /// <summary>
        /// Contains the column numbers for each property in the SQLiteDataReader.
        /// </summary>
        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int ExchangeId = 1;
            public readonly static int SessionType = 2;
            public readonly static int DayOfWeek = 3;
            public readonly static int LocalOpen = 4;
            public readonly static int LocalClose = 5;
        }

        /// <summary>
        /// Contains the names of all columns in the SQLiteDataReader.
        /// </summary>
        public readonly string[] ColumnNames = new[] {
            "Id",
            "ExchangeId",
            "SessionType",
            "DayOfWeek",
            "LocalOpen",
            "LocalClose"
        };
    }
}
