//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using TD.Helpers;
using TD.Models;
using TD.RepositoryContracts;
using TD.SQLite.Extensions;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for Symbol CRUD operations.
    /// </summary>
    public partial class SymbolRepository : AbstractDatabaseRepository<Symbol>, ISymbolRepository
    {
        public SymbolRepository(string databasePath, IExchangeRepository? exchangeRepository = null,
                                ICurrencyRepository? currencyRepository = null) : base(databasePath, "Symbols")

        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            _databasePath = databasePath;
            if (exchangeRepository != null)
                _exchangeRepository = exchangeRepository;
            if (currencyRepository != null)
                _currencyRepository = currencyRepository;

            InitializeDatabase();
            OnInitialized(exchangeRepository == null, currencyRepository == null);
        }
        private readonly string _databasePath;
        private readonly string _selectStatement;

        protected IExchangeRepository ExchangeRepository
        {
            get
            {
                if (_exchangeRepository == null)
                {
                    _exchangeRepository = new ExchangeRepository(_databasePath);
                }
                return _exchangeRepository;
            }
        }
        private IExchangeRepository? _exchangeRepository;

        protected ICurrencyRepository CurrencyRepository
        {
            get
            {
                if (_currencyRepository == null)
                {
                    _currencyRepository = new CurrencyRepository(_databasePath);
                }
                return _currencyRepository;
            }
        }
        private ICurrencyRepository? _currencyRepository;

        protected ITradeRepository TradeRepository
        {
            get
            {
                if (_tradeRepository == null)
                {
                    _tradeRepository = new TradeRepository(_databasePath, symbolRepository: this);
                }
                return _tradeRepository;
            }
        }
        private ITradeRepository? _tradeRepository;


        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "Symbol.sql");
            SeedIfEmpty(connection, "Symbols-Data.sql");
        }

        /// <summary>
        /// Initialization hook for additional setup after the repository is constructed.
        /// The parameters indicate whether the corresponding repository was created by this repository (true) or provided externally (false),
        /// which can be useful to determine if any additional initialization or event wiring is needed.
        /// </summary>
        partial void OnInitialized(bool isExchangeRepository, bool isCurrencyRepository);

        public async Task<IReadOnlyList<Symbol>> GetAllAsync(bool? isActive = null)
        {
            var result = new List<Symbol>();
            var exchangesById = (await ExchangeRepository.GetAllAsync()).ToDictionary(item => item.Id);
            var currenciesById = (await CurrencyRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            if (isActive.HasValue)
            {
                command.CommandText += " WHERE IsActive = @isActive";
                command.AddParameter("@isActive", isActive.Value);
            }

            command.CommandText += " ORDER BY DisplayOrder, TickerFull";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var symbol = MapSymbol(reader);
                if (exchangesById.TryGetValue(symbol.ExchangeId, out var exchange))
                    symbol.Exchange = exchange;

                if (currenciesById.TryGetValue(symbol.PriceCurrencyId, out var priceCurrency))
                    symbol.PriceCurrency = priceCurrency;

                result.Add(symbol);
            }

            return result;
        }

        public async Task<bool> AnyByExchangeIdAsync(int exchangeId)
        {
            if (exchangeId < 1)
                return false;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"SELECT COUNT(1) FROM {_tableName} WHERE ExchangeId = @exchangeId";
            command.Parameters.AddWithValue("@exchangeId", exchangeId);
            var result = await command.ExecuteScalarAsync();
            return Convert.ToInt64(result) > 0;
        }


        public async Task<IReadOnlyList<Symbol>> GetByExchangeIdAsync(int exchangeId, bool? isActive = null)
        {
            var result = new List<Symbol>();
            var exchangesById = (await ExchangeRepository.GetAllAsync()).ToDictionary(item => item.Id);
            var currenciesById = (await CurrencyRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE ExchangeId = @exchangeId";
            command.AddParameter("@exchangeId", exchangeId);
            if (isActive.HasValue)
            {
                command.CommandText += " AND IsActive = @isActive";
                command.AddParameter("@isActive", isActive.Value);
            }

            command.CommandText += " ORDER BY DisplayOrder, TickerFull";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var symbol = MapSymbol(reader);
                if (exchangesById.TryGetValue(symbol.ExchangeId, out var exchange))
                    symbol.Exchange = exchange;

                if (currenciesById.TryGetValue(symbol.PriceCurrencyId, out var priceCurrency))
                    symbol.PriceCurrency = priceCurrency;

                result.Add(symbol);
            }

            return result;
        }


        public async Task<bool> AnyByPriceCurrencyIdAsync(int priceCurrencyId)
        {
            if (priceCurrencyId < 1)
                return false;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"SELECT COUNT(1) FROM {_tableName} WHERE PriceCurrencyId = @priceCurrencyId";
            command.Parameters.AddWithValue("@priceCurrencyId", priceCurrencyId);
            var result = await command.ExecuteScalarAsync();
            return Convert.ToInt64(result) > 0;
        }


        public async Task<IReadOnlyList<Symbol>> GetByPriceCurrencyIdAsync(int priceCurrencyId, bool? isActive = null)
        {
            var result = new List<Symbol>();
            var exchangesById = (await ExchangeRepository.GetAllAsync()).ToDictionary(item => item.Id);
            var currenciesById = (await CurrencyRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE PriceCurrencyId = @priceCurrencyId";
            command.AddParameter("@priceCurrencyId", priceCurrencyId);
            if (isActive.HasValue)
            {
                command.CommandText += " AND IsActive = @isActive";
                command.AddParameter("@isActive", isActive.Value);
            }

            command.CommandText += " ORDER BY DisplayOrder, TickerFull";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var symbol = MapSymbol(reader);
                if (exchangesById.TryGetValue(symbol.ExchangeId, out var exchange))
                    symbol.Exchange = exchange;

                if (currenciesById.TryGetValue(symbol.PriceCurrencyId, out var priceCurrency))
                    symbol.PriceCurrency = priceCurrency;

                result.Add(symbol);
            }

            return result;
        }


        public async Task<Symbol?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var symbol = MapSymbol(reader);
            await LoadExchangeAsync(symbol);
            await LoadCurrencyAsync(symbol);

            OnLoaded(symbol);
            return symbol;
        }

        public async Task<Symbol?> GetByTickerFullAsync(string? tickerFull)
        {
            if (string.IsNullOrWhiteSpace(tickerFull))
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE TickerFull = @tickerFull";
            command.Parameters.AddWithValue("@tickerFull", tickerFull);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var symbol = MapSymbol(reader);
            await LoadExchangeAsync(symbol);
            await LoadCurrencyAsync(symbol);

            OnLoaded(symbol);
            return symbol;
        }
        partial void OnLoaded(Symbol symbol);

        public async Task<IReadOnlyList<Symbol>> GetPagedAsync(QueryParameters queryParameters, bool? isActive = null)
        {
            ArgumentNullException.ThrowIfNull(queryParameters);

            var result = new List<Symbol>();
            var exchangesById = (await ExchangeRepository.GetAllAsync()).ToDictionary(item => item.Id);
            var currenciesById = (await CurrencyRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            if (isActive.HasValue)
            {
                command.CommandText += " WHERE IsActive = @isActive";
                command.Parameters.AddWithValue("@isActive", isActive.Value);
            }

            command.CommandText += " ORDER BY DisplayOrder, TickerFull";
            command.CommandText += " LIMIT @pageSize OFFSET @skip";
            command.Parameters.AddWithValue("@pageSize", queryParameters.PageSize);
            command.Parameters.AddWithValue("@skip", queryParameters.Skip);

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var symbol = MapSymbol(reader);
                if (exchangesById.TryGetValue(symbol.ExchangeId, out var exchange))
                    symbol.Exchange = exchange;

                if (currenciesById.TryGetValue(symbol.PriceCurrencyId, out var priceCurrency))
                    symbol.PriceCurrency = priceCurrency;

                result.Add(symbol);
            }

            await using var countCommand = connection.CreateCommand();
            countCommand.CommandText = $"SELECT COUNT(1) FROM {_tableName}";
            if (isActive.HasValue)
            {
                countCommand.CommandText += " WHERE IsActive = @isActive";
                countCommand.Parameters.AddWithValue("@isActive", isActive.Value);
            }
            queryParameters.TotalCount = Convert.ToInt64(await countCommand.ExecuteScalarAsync());

            return result;
        }

        public async Task<int> CreateAsync(Symbol symbol)
        {
            ArgumentNullException.ThrowIfNull(symbol);
            ValidateOrThrow(symbol);

            await using var connection = await GetOpenConnectionAsync();
            var existingSymbol = await GetByTickerFullAsync(symbol.TickerFull);
            if (existingSymbol != null)
            {
                symbol.Id = existingSymbol.Id;
                await UpdateAsync(symbol);
                return existingSymbol.Id;
            }

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@ticker, @tickerFull, @baseCurrency, @priceCurrencyId, @description, @exchangeId,
                    @marketType, @displayOrder, @isActive);
            SELECT last_insert_rowid();";

            command.AddParameter("@ticker", symbol.Ticker);
            command.AddParameter("@tickerFull", symbol.TickerFull);
            command.AddNullableParameter("@baseCurrency", symbol.BaseCurrency);
            command.AddParameter("@priceCurrencyId", symbol.PriceCurrencyId);
            command.AddNullableParameter("@description", symbol.Description);
            command.AddParameter("@exchangeId", symbol.ExchangeId);
            command.AddParameter("@marketType", (int)symbol.MarketType);
            command.AddParameter("@displayOrder", symbol.DisplayOrder);
            command.AddParameter("@isActive", symbol.IsActive);

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));

            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            symbol.Id = id;
            OnCreated(symbol);

            return id;
        }
        partial void OnCreated(Symbol symbol);

        /// <summary>
        /// Determines whether a symbol can be safely deleted based on the absence of related records.
        /// </summary>
        /// <remarks>A symbol can be deleted only if there are no associated records. Use this method
        /// before attempting to delete a symbol to avoid violating referential integrity.</remarks>
        /// <param name="id">The identifier of the symbol record to check for deletability.</param>
        /// <returns>A task that represents the asynchronous operation. The task result is <see langword="true"/> if the symbol
        /// can be deleted; otherwise, <see langword="false"/>.</returns>
        public async Task<bool> CanDeleteAsync(int id)
        {
            if (id < 1)
                return false;

            bool result = true;

            // Checking any trade record exists through Trade.SymbolId reference
            result = result && !(await TradeRepository.AnyBySymbolIdAsync(id));

            return result;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(Symbol symbol)
        {
            ArgumentNullException.ThrowIfNull(symbol);
            ValidateOrThrow(symbol);

            await using var connection = await GetOpenConnectionAsync();
            var existingSymbol = await GetByTickerFullAsync(symbol.TickerFull);
            if (existingSymbol != null && existingSymbol.Id != symbol.Id)
            {
                throw new InvalidOperationException($"A different Symbol with the same TickerFull already exists: {symbol.TickerFull}");
            }

            existingSymbol = await GetByIdAsync(symbol.Id);
            bool noChanges = existingSymbol != null
                          && existingSymbol.Description == symbol.Description
                          && existingSymbol.MarketType == symbol.MarketType
                          && existingSymbol.DisplayOrder == symbol.DisplayOrder
                          && existingSymbol.IsActive == symbol.IsActive;

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // Ticker, TickerFull, BaseCurrency, PriceCurrencyId, ExchangeId are not updated to avoid complications with existing references,
            // so only Description, MarketType, DisplayOrder, IsActive are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                Description = @description,
                MarketType = @marketType,
                DisplayOrder = @displayOrder,
                IsActive = @isActive
            WHERE Id = @id";

            command.AddParameter("@id", symbol.Id);
            command.AddNullableParameter("@description", symbol.Description);
            command.AddParameter("@marketType", (int)symbol.MarketType);
            command.AddParameter("@displayOrder", symbol.DisplayOrder);
            command.AddParameter("@isActive", symbol.IsActive);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(symbol);
            }

            return affectedRows > 0;
        }
        partial void OnUpdated(Symbol symbol);

        private async Task LoadExchangeAsync(Symbol symbol)
        {
            symbol.Exchange = await ExchangeRepository.GetByIdAsync(symbol.ExchangeId)
                            ?? new Exchange { Id = symbol.ExchangeId };
        }


        private async Task LoadCurrencyAsync(Symbol symbol)
        {
            symbol.PriceCurrency = await CurrencyRepository.GetByIdAsync(symbol.PriceCurrencyId)
                            ?? new Currency { Id = symbol.PriceCurrencyId };
        }


        private static Symbol MapSymbol(SqliteDataReader reader)
        {
            var symbol = new Symbol
            {
                Id = reader.GetInt32(ColNrs.Id),
                Ticker = reader.GetString(ColNrs.Ticker),
                TickerFull = reader.GetString(ColNrs.TickerFull),
                BaseCurrency = reader.IsDBNull(ColNrs.BaseCurrency) ? null
                             : reader.GetString(ColNrs.BaseCurrency),
                PriceCurrencyId = reader.GetInt32(ColNrs.PriceCurrencyId),
                Description = reader.IsDBNull(ColNrs.Description) ? null
                            : reader.GetString(ColNrs.Description),
                ExchangeId = reader.GetInt32(ColNrs.ExchangeId),
                MarketType = (MarketType)reader.GetInt32(ColNrs.MarketType),
                DisplayOrder = reader.GetInt32(ColNrs.DisplayOrder),
                IsActive = reader.GetInt64(ColNrs.IsActive) == 1
            };

            return symbol;
        }

        /// <summary>
        /// Contains the column numbers for each property in the SQLiteDataReader.
        /// </summary>
        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int Ticker = 1;
            public readonly static int TickerFull = 2;
            public readonly static int BaseCurrency = 3;
            public readonly static int PriceCurrencyId = 4;
            public readonly static int Description = 5;
            public readonly static int ExchangeId = 6;
            public readonly static int MarketType = 7;
            public readonly static int DisplayOrder = 8;
            public readonly static int IsActive = 9;
        }

        /// <summary>
        /// Contains the names of all columns in the SQLiteDataReader.
        /// </summary>
        public readonly string[] ColumnNames = new[] {
            "Id",
            "Ticker",
            "TickerFull",
            "BaseCurrency",
            "PriceCurrencyId",
            "Description",
            "ExchangeId",
            "MarketType",
            "DisplayOrder",
            "IsActive"
        };
    }
}
