//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using Microsoft.Data.Sqlite;
using TD.Models;
using TD.RepositoryContracts;
using TD.SQLite.Extensions;

namespace TD.SQLite
{
    /// <summary>
    /// SQLite-based repository for TradingAccount CRUD operations.
    /// </summary>
    public partial class TradingAccountRepository : AbstractDatabaseRepository<TradingAccount>, ITradingAccountRepository
    {
        public TradingAccountRepository(string databasePath, IExchangeRepository? exchangeRepository = null) : base(databasePath, "TradingAccounts")

        {
            _selectStatement = $"SELECT {string.Join(", ", ColumnNames)} FROM {_tableName}";
            _databasePath = databasePath;
            if (exchangeRepository != null)
                _exchangeRepository = exchangeRepository;

            InitializeDatabase();
            OnInitialized(exchangeRepository == null);
        }
        private readonly string _databasePath;
        private readonly string _selectStatement;

        protected IExchangeRepository ExchangeRepository
        {
            get
            {
                if (_exchangeRepository == null)
                {
                    _exchangeRepository = new ExchangeRepository(_databasePath);
                }
                return _exchangeRepository;
            }
        }
        private IExchangeRepository? _exchangeRepository;

        protected ITradeRepository TradeRepository
        {
            get
            {
                if (_tradeRepository == null)
                {
                    _tradeRepository = new TradeRepository(_databasePath, tradingAccountRepository: this);
                }
                return _tradeRepository;
            }
        }
        private ITradeRepository? _tradeRepository;


        private void InitializeDatabase()
        {
            using var connection = GetOpenConnection();
            ExecuteScript(connection, "TradingAccount.sql");
        }

        /// <summary>
        /// Initialization hook for additional setup after the repository is constructed.
        /// The parameters indicate whether the corresponding repository was created by this repository (true) or provided externally (false),
        /// which can be useful to determine if any additional initialization or event wiring is needed.
        /// </summary>
        partial void OnInitialized(bool isExchangeRepository);

        public async Task<IReadOnlyList<TradingAccount>> GetAllAsync(bool? isActive = null)
        {
            var result = new List<TradingAccount>();
            var exchangesById = (await ExchangeRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            if (isActive.HasValue)
            {
                command.CommandText += " WHERE IsActive = @isActive";
                command.AddParameter("@isActive", isActive.Value);
            }

            command.CommandText += " ORDER BY DisplayOrder, Title";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var tradingAccount = MapTradingAccount(reader);
                if (exchangesById.TryGetValue(tradingAccount.ExchangeId, out var exchange))
                    tradingAccount.Exchange = exchange;

                result.Add(tradingAccount);
            }

            return result;
        }

        public async Task<bool> AnyByExchangeIdAsync(int exchangeId)
        {
            if (exchangeId < 1)
                return false;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"SELECT COUNT(1) FROM {_tableName} WHERE ExchangeId = @exchangeId";
            command.Parameters.AddWithValue("@exchangeId", exchangeId);
            var result = await command.ExecuteScalarAsync();
            return Convert.ToInt64(result) > 0;
        }


        public async Task<IReadOnlyList<TradingAccount>> GetByExchangeIdAsync(int exchangeId, bool? isActive = null)
        {
            var result = new List<TradingAccount>();
            var exchangesById = (await ExchangeRepository.GetAllAsync()).ToDictionary(item => item.Id);

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = _selectStatement;
            command.CommandText += " WHERE ExchangeId = @exchangeId";
            command.AddParameter("@exchangeId", exchangeId);
            if (isActive.HasValue)
            {
                command.CommandText += " AND IsActive = @isActive";
                command.AddParameter("@isActive", isActive.Value);
            }

            command.CommandText += " ORDER BY DisplayOrder, Title";

            await using var reader = await command.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                var tradingAccount = MapTradingAccount(reader);
                if (exchangesById.TryGetValue(tradingAccount.ExchangeId, out var exchange))
                    tradingAccount.Exchange = exchange;

                result.Add(tradingAccount);
            }

            return result;
        }


        public async Task<TradingAccount?> GetByIdAsync(int? id)
        {
            if (!id.HasValue || id.Value < 1)
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var tradingAccount = MapTradingAccount(reader);
            await LoadExchangeAsync(tradingAccount);

            OnLoaded(tradingAccount);
            return tradingAccount;
        }

        public async Task<TradingAccount?> GetByTitleAsync(string? title)
        {
            if (string.IsNullOrWhiteSpace(title))
                return null;

            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $@"{_selectStatement}
            WHERE Title = @title";
            command.Parameters.AddWithValue("@title", title);

            await using var reader = await command.ExecuteReaderAsync();
            if (!await reader.ReadAsync())
                return null;

            var tradingAccount = MapTradingAccount(reader);
            await LoadExchangeAsync(tradingAccount);

            OnLoaded(tradingAccount);
            return tradingAccount;
        }
        partial void OnLoaded(TradingAccount tradingAccount);

        public async Task<int> CreateAsync(TradingAccount tradingAccount)
        {
            ArgumentNullException.ThrowIfNull(tradingAccount);
            ValidateOrThrow(tradingAccount);

            await using var connection = await GetOpenConnectionAsync();
            var existingTradingAccount = await GetByTitleAsync(tradingAccount.Title);
            if (existingTradingAccount != null)
            {
                tradingAccount.Id = existingTradingAccount.Id;
                await UpdateAsync(tradingAccount);
                return existingTradingAccount.Id;
            }

            await using var command = connection.CreateCommand();
            command.CommandText = @$"INSERT INTO {_tableName} ({string.Join(", ", ColumnNames[1..])})
            VALUES (@title, @exchangeId, @marketType, @makerFeeRate, @takerFeeRate, @notes,
                    @displayOrder, @isActive);
            SELECT last_insert_rowid();";

            command.AddParameter("@title", tradingAccount.Title);
            command.AddParameter("@exchangeId", tradingAccount.ExchangeId);
            command.AddParameter("@marketType", (int)tradingAccount.MarketType);
            command.AddDecimalToTextParameter("@makerFeeRate", tradingAccount.MakerFeeRate);
            command.AddDecimalToTextParameter("@takerFeeRate", tradingAccount.TakerFeeRate);
            command.AddNullableParameter("@notes", tradingAccount.Notes);
            command.AddParameter("@displayOrder", tradingAccount.DisplayOrder);
            command.AddParameter("@isActive", tradingAccount.IsActive);

            var id = Convert.ToInt32((long)(await command.ExecuteScalarAsync() ?? 0));

            await _metadataRepository.SaveLastUpdateUtcAsync(connection);
            ClearRecordCountCache();
            tradingAccount.Id = id;
            OnCreated(tradingAccount);

            return id;
        }
        partial void OnCreated(TradingAccount tradingAccount);

        /// <summary>
        /// Determines whether a tradingAccount can be safely deleted based on the absence of related records.
        /// </summary>
        /// <remarks>A tradingAccount can be deleted only if there are no associated records. Use this method
        /// before attempting to delete a tradingAccount to avoid violating referential integrity.</remarks>
        /// <param name="id">The identifier of the tradingAccount record to check for deletability.</param>
        /// <returns>A task that represents the asynchronous operation. The task result is <see langword="true"/> if the tradingAccount
        /// can be deleted; otherwise, <see langword="false"/>.</returns>
        public async Task<bool> CanDeleteAsync(int id)
        {
            if (id < 1)
                return false;

            bool result = true;

            // Checking any trade record exists through Trade.TradingAccountId reference
            result = result && !(await TradeRepository.AnyByTradingAccountIdAsync(id));

            return result;
        }

        public async Task<bool> DeleteAsync(int id)
        {
            await using var connection = await GetOpenConnectionAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"DELETE FROM {_tableName} WHERE Id = @id";
            command.Parameters.AddWithValue("@id", id);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                ClearRecordCountCache();
            }

            return affectedRows > 0;
        }

        public async Task<bool> UpdateAsync(TradingAccount tradingAccount)
        {
            ArgumentNullException.ThrowIfNull(tradingAccount);
            ValidateOrThrow(tradingAccount);

            await using var connection = await GetOpenConnectionAsync();
            var existingTradingAccount = await GetByTitleAsync(tradingAccount.Title);
            if (existingTradingAccount != null && existingTradingAccount.Id != tradingAccount.Id)
            {
                throw new InvalidOperationException($"A different TradingAccount with the same Title already exists: {tradingAccount.Title}");
            }

            existingTradingAccount = await GetByIdAsync(tradingAccount.Id);
            bool noChanges = existingTradingAccount != null
                          && existingTradingAccount.Title == tradingAccount.Title
                          && existingTradingAccount.MarketType == tradingAccount.MarketType
                          && existingTradingAccount.MakerFeeRate == tradingAccount.MakerFeeRate
                          && existingTradingAccount.TakerFeeRate == tradingAccount.TakerFeeRate
                          && existingTradingAccount.Notes == tradingAccount.Notes
                          && existingTradingAccount.DisplayOrder == tradingAccount.DisplayOrder
                          && existingTradingAccount.IsActive == tradingAccount.IsActive;

            if (noChanges)
                return false;

            await using var command = connection.CreateCommand();
            // ExchangeId is not updated to avoid complications with existing references,
            // so only Title, MarketType, MakerFeeRate, TakerFeeRate, Notes, DisplayOrder, IsActive are updated
            command.CommandText = @$"UPDATE {_tableName} SET
                Title = @title,
                MarketType = @marketType,
                MakerFeeRate = @makerFeeRate,
                TakerFeeRate = @takerFeeRate,
                Notes = @notes,
                DisplayOrder = @displayOrder,
                IsActive = @isActive
            WHERE Id = @id";

            command.AddParameter("@id", tradingAccount.Id);
            command.AddParameter("@title", tradingAccount.Title);
            command.AddParameter("@marketType", (int)tradingAccount.MarketType);
            command.AddDecimalToTextParameter("@makerFeeRate", tradingAccount.MakerFeeRate);
            command.AddDecimalToTextParameter("@takerFeeRate", tradingAccount.TakerFeeRate);
            command.AddNullableParameter("@notes", tradingAccount.Notes);
            command.AddParameter("@displayOrder", tradingAccount.DisplayOrder);
            command.AddParameter("@isActive", tradingAccount.IsActive);

            var affectedRows = await command.ExecuteNonQueryAsync();
            if (affectedRows > 0)
            {
                await _metadataRepository.SaveLastUpdateUtcAsync(connection);
                OnUpdated(tradingAccount);
            }

            return affectedRows > 0;
        }
        partial void OnUpdated(TradingAccount tradingAccount);

        private async Task LoadExchangeAsync(TradingAccount tradingAccount)
        {
            tradingAccount.Exchange = await ExchangeRepository.GetByIdAsync(tradingAccount.ExchangeId)
                            ?? new Exchange { Id = tradingAccount.ExchangeId };
        }


        private static TradingAccount MapTradingAccount(SqliteDataReader reader)
        {
            var tradingAccount = new TradingAccount
            {
                Id = reader.GetInt32(ColNrs.Id),
                Title = reader.GetString(ColNrs.Title),
                ExchangeId = reader.GetInt32(ColNrs.ExchangeId),
                MarketType = (MarketType)reader.GetInt32(ColNrs.MarketType),
                MakerFeeRate = reader.IsDBNull(ColNrs.MakerFeeRate) ? null
                             : reader.GetDecimalFromText(ColNrs.MakerFeeRate),
                TakerFeeRate = reader.IsDBNull(ColNrs.TakerFeeRate) ? null
                             : reader.GetDecimalFromText(ColNrs.TakerFeeRate),
                Notes = reader.IsDBNull(ColNrs.Notes) ? null
                      : reader.GetString(ColNrs.Notes),
                DisplayOrder = reader.GetInt32(ColNrs.DisplayOrder),
                IsActive = reader.GetInt64(ColNrs.IsActive) == 1
            };

            return tradingAccount;
        }

        /// <summary>
        /// Contains the column numbers for each property in the SQLiteDataReader.
        /// </summary>
        public readonly struct ColNrs
        {
            public readonly static int Id = 0;
            public readonly static int Title = 1;
            public readonly static int ExchangeId = 2;
            public readonly static int MarketType = 3;
            public readonly static int MakerFeeRate = 4;
            public readonly static int TakerFeeRate = 5;
            public readonly static int Notes = 6;
            public readonly static int DisplayOrder = 7;
            public readonly static int IsActive = 8;
        }

        /// <summary>
        /// Contains the names of all columns in the SQLiteDataReader.
        /// </summary>
        public readonly string[] ColumnNames = new[] {
            "Id",
            "Title",
            "ExchangeId",
            "MarketType",
            "MakerFeeRate",
            "TakerFeeRate",
            "Notes",
            "DisplayOrder",
            "IsActive"
        };

        /// <summary>
        /// Contains the scale values used for converting decimal properties to integer storage.
        /// </summary>
        public readonly struct DecimalToIntegerScale
        {
            public readonly static int MakerFeeRate = 0;
            public readonly static int TakerFeeRate = 0;
        }
    }
}
