//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TD.i18n.ErrorStrings", typeof(ErrorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field cannot be before than {1}..
        /// </summary>
        public static string DateGreaterThan {
            get {
                return ResourceManager.GetString("DateGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be before than {2}..
        /// </summary>
        public static string DateLessThan {
            get {
                return ResourceManager.GetString("DateLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled price must be greater than zero when filled quantity is specified..
        /// </summary>
        public static string FilledPriceWhenFilledQuantityHasValue {
            get {
                return ResourceManager.GetString("FilledPriceWhenFilledQuantityHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled quantity cannot exceed the remaining open quantity ({0}) of the trade..
        /// </summary>
        public static string FilledQuantityExceedsRemaining {
            get {
                return ResourceManager.GetString("FilledQuantityExceedsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled quantity must be greater than zero when filled price is specified..
        /// </summary>
        public static string FilledQuantityWhenFilledPriceHasValue {
            get {
                return ResourceManager.GetString("FilledQuantityWhenFilledPriceHasValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field maximum length is {1}..
        /// </summary>
        public static string MaxStringLength {
            get {
                return ResourceManager.GetString("MaxStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When {0} field is filled {1} is required {2} or further selection..
        /// </summary>
        public static string MinSelectionWhenOtherFilled {
            get {
                return ResourceManager.GetString("MinSelectionWhenOtherFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string MinStringLength {
            get {
                return ResourceManager.GetString("MinStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string NewPasswordNotMatch {
            get {
                return ResourceManager.GetString("NewPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field field must be above the entry price ({1})..
        /// </summary>
        public static string PriceSideMustBeAbove {
            get {
                return ResourceManager.GetString("PriceSideMustBeAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field field must be below the entry price ({1})..
        /// </summary>
        public static string PriceSideMustBeBelow {
            get {
                return ResourceManager.GetString("PriceSideMustBeBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be between {1} and {2}..
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be between {1} and {2}..
        /// </summary>
        public static string RangeDateTime {
            get {
                return ResourceManager.GetString("RangeDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be between {1} and {2}..
        /// </summary>
        public static string RangeDecimal {
            get {
                return ResourceManager.GetString("RangeDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be between {1} and {2}..
        /// </summary>
        public static string RangeInt {
            get {
                return ResourceManager.GetString("RangeInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address to {0} field..
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredEnum {
            get {
                return ResourceManager.GetString("RequiredEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password to {0} field..
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required when {1} is filled..
        /// </summary>
        public static string RequiredWhenOtherFilled {
            get {
                return ResourceManager.GetString("RequiredWhenOtherFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required when {1} selected in {2}..
        /// </summary>
        public static string RequiredWhenOtherSelected {
            get {
                return ResourceManager.GetString("RequiredWhenOtherSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be greater than {1}..
        /// </summary>
        public static string ValueGreaterThan {
            get {
                return ResourceManager.GetString("ValueGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be less than {2}..
        /// </summary>
        public static string ValueLessThan {
            get {
                return ResourceManager.GetString("ValueLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be less than or equal to {2}..
        /// </summary>
        public static string ValueMax {
            get {
                return ResourceManager.GetString("ValueMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field must be greater than or equal to {1}..
        /// </summary>
        public static string ValueMin {
            get {
                return ResourceManager.GetString("ValueMin", resourceCulture);
            }
        }
    }
}
