//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TD.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TD.i18n.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Or Waiting.
        /// </summary>
        public static string ActiveOrWaiting {
            get {
                return ResourceManager.GetString("ActiveOrWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Currency.
        /// </summary>
        public static string AddCurrency {
            get {
                return ResourceManager.GetString("AddCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Entry Order.
        /// </summary>
        public static string AddEntryOrder {
            get {
                return ResourceManager.GetString("AddEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Exchange.
        /// </summary>
        public static string AddExchange {
            get {
                return ResourceManager.GetString("AddExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Holiday.
        /// </summary>
        public static string AddHoliday {
            get {
                return ResourceManager.GetString("AddHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Currency.
        /// </summary>
        public static string AddNewCurrency {
            get {
                return ResourceManager.GetString("AddNewCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Entry Order.
        /// </summary>
        public static string AddNewEntryOrder {
            get {
                return ResourceManager.GetString("AddNewEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Exchange.
        /// </summary>
        public static string AddNewExchange {
            get {
                return ResourceManager.GetString("AddNewExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Holiday.
        /// </summary>
        public static string AddNewHoliday {
            get {
                return ResourceManager.GetString("AddNewHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Session.
        /// </summary>
        public static string AddNewSession {
            get {
                return ResourceManager.GetString("AddNewSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Stop Loss Order.
        /// </summary>
        public static string AddNewStopLossOrder {
            get {
                return ResourceManager.GetString("AddNewStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Symbol.
        /// </summary>
        public static string AddNewSymbol {
            get {
                return ResourceManager.GetString("AddNewSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Take Profit Order.
        /// </summary>
        public static string AddNewTakeProfitOrder {
            get {
                return ResourceManager.GetString("AddNewTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Trade.
        /// </summary>
        public static string AddNewTrade {
            get {
                return ResourceManager.GetString("AddNewTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Trade Image.
        /// </summary>
        public static string AddNewTradeImage {
            get {
                return ResourceManager.GetString("AddNewTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Trading Account.
        /// </summary>
        public static string AddNewTradingAccount {
            get {
                return ResourceManager.GetString("AddNewTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Currency.
        /// </summary>
        public static string AddRemoveCurrency {
            get {
                return ResourceManager.GetString("AddRemoveCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Entry Order.
        /// </summary>
        public static string AddRemoveEntryOrder {
            get {
                return ResourceManager.GetString("AddRemoveEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Exchange.
        /// </summary>
        public static string AddRemoveExchange {
            get {
                return ResourceManager.GetString("AddRemoveExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Holiday.
        /// </summary>
        public static string AddRemoveHoliday {
            get {
                return ResourceManager.GetString("AddRemoveHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Session.
        /// </summary>
        public static string AddRemoveSession {
            get {
                return ResourceManager.GetString("AddRemoveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Stop Loss Order.
        /// </summary>
        public static string AddRemoveStopLossOrder {
            get {
                return ResourceManager.GetString("AddRemoveStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Symbol.
        /// </summary>
        public static string AddRemoveSymbol {
            get {
                return ResourceManager.GetString("AddRemoveSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Take Profit Order.
        /// </summary>
        public static string AddRemoveTakeProfitOrder {
            get {
                return ResourceManager.GetString("AddRemoveTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Trade.
        /// </summary>
        public static string AddRemoveTrade {
            get {
                return ResourceManager.GetString("AddRemoveTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Trade Image.
        /// </summary>
        public static string AddRemoveTradeImage {
            get {
                return ResourceManager.GetString("AddRemoveTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remove Trading Account.
        /// </summary>
        public static string AddRemoveTradingAccount {
            get {
                return ResourceManager.GetString("AddRemoveTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Session.
        /// </summary>
        public static string AddSession {
            get {
                return ResourceManager.GetString("AddSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Stop Loss Order.
        /// </summary>
        public static string AddStopLossOrder {
            get {
                return ResourceManager.GetString("AddStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Symbol.
        /// </summary>
        public static string AddSymbol {
            get {
                return ResourceManager.GetString("AddSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Take Profit Order.
        /// </summary>
        public static string AddTakeProfitOrder {
            get {
                return ResourceManager.GetString("AddTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trade.
        /// </summary>
        public static string AddTrade {
            get {
                return ResourceManager.GetString("AddTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trade Image.
        /// </summary>
        public static string AddTradeImage {
            get {
                return ResourceManager.GetString("AddTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trading Account.
        /// </summary>
        public static string AddTradingAccount {
            get {
                return ResourceManager.GetString("AddTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Hours.
        /// </summary>
        public static string AfterHours {
            get {
                return ResourceManager.GetString("AfterHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Dates.
        /// </summary>
        public static string AllDates {
            get {
                return ResourceManager.GetString("AllDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        public static string BaseCurrency {
            get {
                return ResourceManager.GetString("BaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        public static string Boolean {
            get {
                return ResourceManager.GetString("Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation Time.
        /// </summary>
        public static string CancellationTime {
            get {
                return ResourceManager.GetString("CancellationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing Auction.
        /// </summary>
        public static string ClosingAuction {
            get {
                return ResourceManager.GetString("ClosingAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity.
        /// </summary>
        public static string Commodity {
            get {
                return ResourceManager.GetString("Commodity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Currency.
        /// </summary>
        public static string CreateCurrency {
            get {
                return ResourceManager.GetString("CreateCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Entry Order.
        /// </summary>
        public static string CreateEntryOrder {
            get {
                return ResourceManager.GetString("CreateEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Exchange.
        /// </summary>
        public static string CreateExchange {
            get {
                return ResourceManager.GetString("CreateExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Holiday.
        /// </summary>
        public static string CreateHoliday {
            get {
                return ResourceManager.GetString("CreateHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Session.
        /// </summary>
        public static string CreateSession {
            get {
                return ResourceManager.GetString("CreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Stop Loss Order.
        /// </summary>
        public static string CreateStopLossOrder {
            get {
                return ResourceManager.GetString("CreateStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Symbol.
        /// </summary>
        public static string CreateSymbol {
            get {
                return ResourceManager.GetString("CreateSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Take Profit Order.
        /// </summary>
        public static string CreateTakeProfitOrder {
            get {
                return ResourceManager.GetString("CreateTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Trade.
        /// </summary>
        public static string CreateTrade {
            get {
                return ResourceManager.GetString("CreateTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Trade Image.
        /// </summary>
        public static string CreateTradeImage {
            get {
                return ResourceManager.GetString("CreateTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Trading Account.
        /// </summary>
        public static string CreateTradingAccount {
            get {
                return ResourceManager.GetString("CreateTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Perpetual.
        /// </summary>
        public static string CryptoPerpetual {
            get {
                return ResourceManager.GetString("CryptoPerpetual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto Spot.
        /// </summary>
        public static string CryptoSpot {
            get {
                return ResourceManager.GetString("CryptoSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies List.
        /// </summary>
        public static string CurrenciesList {
            get {
                return ResourceManager.GetString("CurrenciesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Ticker.
        /// </summary>
        public static string CurrencyTicker {
            get {
                return ResourceManager.GetString("CurrencyTicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Array.
        /// </summary>
        public static string DateArray {
            get {
                return ResourceManager.GetString("DateArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Period.
        /// </summary>
        public static string DatePeriod {
            get {
                return ResourceManager.GetString("DatePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Time Array.
        /// </summary>
        public static string DateTimeArray {
            get {
                return ResourceManager.GetString("DateTimeArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Of Week.
        /// </summary>
        public static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        public static string Decimal {
            get {
                return ResourceManager.GetString("Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal Array.
        /// </summary>
        public static string DecimalArray {
            get {
                return ResourceManager.GetString("DecimalArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Currency.
        /// </summary>
        public static string DefaultCurrency {
            get {
                return ResourceManager.GetString("DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Currency.
        /// </summary>
        public static string DefaultCurrencyId {
            get {
                return ResourceManager.GetString("DefaultCurrencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Currency.
        /// </summary>
        public static string DeleteCurrency {
            get {
                return ResourceManager.GetString("DeleteCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Entry Order.
        /// </summary>
        public static string DeleteEntryOrder {
            get {
                return ResourceManager.GetString("DeleteEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Exchange.
        /// </summary>
        public static string DeleteExchange {
            get {
                return ResourceManager.GetString("DeleteExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Holiday.
        /// </summary>
        public static string DeleteHoliday {
            get {
                return ResourceManager.GetString("DeleteHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Session.
        /// </summary>
        public static string DeleteSession {
            get {
                return ResourceManager.GetString("DeleteSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Stop Loss Order.
        /// </summary>
        public static string DeleteStopLossOrder {
            get {
                return ResourceManager.GetString("DeleteStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Symbol.
        /// </summary>
        public static string DeleteSymbol {
            get {
                return ResourceManager.GetString("DeleteSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Take Profit Order.
        /// </summary>
        public static string DeleteTakeProfitOrder {
            get {
                return ResourceManager.GetString("DeleteTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Trade.
        /// </summary>
        public static string DeleteTrade {
            get {
                return ResourceManager.GetString("DeleteTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Trade Image.
        /// </summary>
        public static string DeleteTradeImage {
            get {
                return ResourceManager.GetString("DeleteTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Trading Account.
        /// </summary>
        public static string DeleteTradingAccount {
            get {
                return ResourceManager.GetString("DeleteTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Order.
        /// </summary>
        public static string DisplayOrder {
            get {
                return ResourceManager.GetString("DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Currency.
        /// </summary>
        public static string EditCurrency {
            get {
                return ResourceManager.GetString("EditCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Entry Order.
        /// </summary>
        public static string EditEntryOrder {
            get {
                return ResourceManager.GetString("EditEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Exchange.
        /// </summary>
        public static string EditExchange {
            get {
                return ResourceManager.GetString("EditExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Holiday.
        /// </summary>
        public static string EditHoliday {
            get {
                return ResourceManager.GetString("EditHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Session.
        /// </summary>
        public static string EditSession {
            get {
                return ResourceManager.GetString("EditSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Stop Loss Order.
        /// </summary>
        public static string EditStopLossOrder {
            get {
                return ResourceManager.GetString("EditStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Symbol.
        /// </summary>
        public static string EditSymbol {
            get {
                return ResourceManager.GetString("EditSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Take Profit Order.
        /// </summary>
        public static string EditTakeProfitOrder {
            get {
                return ResourceManager.GetString("EditTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trade.
        /// </summary>
        public static string EditTrade {
            get {
                return ResourceManager.GetString("EditTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trade Image.
        /// </summary>
        public static string EditTradeImage {
            get {
                return ResourceManager.GetString("EditTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trading Account.
        /// </summary>
        public static string EditTradingAccount {
            get {
                return ResourceManager.GetString("EditTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic Trading Hours.
        /// </summary>
        public static string ElectronicTradingHours {
            get {
                return ResourceManager.GetString("ElectronicTradingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Entry {
            get {
                return ResourceManager.GetString("Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Order.
        /// </summary>
        public static string EntryOrder {
            get {
                return ResourceManager.GetString("EntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Orders.
        /// </summary>
        public static string EntryOrders {
            get {
                return ResourceManager.GetString("EntryOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Orders List.
        /// </summary>
        public static string EntryOrdersList {
            get {
                return ResourceManager.GetString("EntryOrdersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Order Type.
        /// </summary>
        public static string EntryOrderType {
            get {
                return ResourceManager.GetString("EntryOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Time.
        /// </summary>
        public static string EntryTime {
            get {
                return ResourceManager.GetString("EntryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Code.
        /// </summary>
        public static string ExchangeCode {
            get {
                return ResourceManager.GetString("ExchangeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange.
        /// </summary>
        public static string ExchangeId {
            get {
                return ResourceManager.GetString("ExchangeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Name.
        /// </summary>
        public static string ExchangeName {
            get {
                return ResourceManager.GetString("ExchangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchanges.
        /// </summary>
        public static string Exchanges {
            get {
                return ResourceManager.GetString("Exchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchanges List.
        /// </summary>
        public static string ExchangesList {
            get {
                return ResourceManager.GetString("ExchangesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed Entry Price.
        /// </summary>
        public static string ExecutedEntryPrice {
            get {
                return ResourceManager.GetString("ExecutedEntryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed Position Value.
        /// </summary>
        public static string ExecutedPositionValue {
            get {
                return ResourceManager.GetString("ExecutedPositionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed SL.
        /// </summary>
        public static string ExecutedSL {
            get {
                return ResourceManager.GetString("ExecutedSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed TP.
        /// </summary>
        public static string ExecutedTP {
            get {
                return ResourceManager.GetString("ExecutedTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Order Type.
        /// </summary>
        public static string ExitOrderType {
            get {
                return ResourceManager.GetString("ExitOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Time.
        /// </summary>
        public static string ExitTime {
            get {
                return ResourceManager.GetString("ExitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees Calculated.
        /// </summary>
        public static string FeesCalculated {
            get {
                return ResourceManager.GetString("FeesCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Price.
        /// </summary>
        public static string FilledPrice {
            get {
                return ResourceManager.GetString("FilledPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Profit Amount.
        /// </summary>
        public static string FilledProfitAmount {
            get {
                return ResourceManager.GetString("FilledProfitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Quantity.
        /// </summary>
        public static string FilledQuantity {
            get {
                return ResourceManager.GetString("FilledQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Risk Amount.
        /// </summary>
        public static string FilledRiskAmount {
            get {
                return ResourceManager.GetString("FilledRiskAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Time.
        /// </summary>
        public static string FilledTime {
            get {
                return ResourceManager.GetString("FilledTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filled Value.
        /// </summary>
        public static string FilledValue {
            get {
                return ResourceManager.GetString("FilledValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forex.
        /// </summary>
        public static string Forex {
            get {
                return ResourceManager.GetString("Forex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fund.
        /// </summary>
        public static string Fund {
            get {
                return ResourceManager.GetString("Fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Fee Total.
        /// </summary>
        public static string FundingFeeTotal {
            get {
                return ResourceManager.GetString("FundingFeeTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Futures.
        /// </summary>
        public static string Futures {
            get {
                return ResourceManager.GetString("Futures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Any Symbol.
        /// </summary>
        public static string HasAnySymbol {
            get {
                return ResourceManager.GetString("HasAnySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Date.
        /// </summary>
        public static string HolidayDate {
            get {
                return ResourceManager.GetString("HolidayDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Name.
        /// </summary>
        public static string HolidayName {
            get {
                return ResourceManager.GetString("HolidayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays.
        /// </summary>
        public static string Holidays {
            get {
                return ResourceManager.GetString("Holidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holidays List.
        /// </summary>
        public static string HolidaysList {
            get {
                return ResourceManager.GetString("HolidaysList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Nr.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL.
        /// </summary>
        public static string ImageURL {
            get {
                return ResourceManager.GetString("ImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        public static string Integer {
            get {
                return ResourceManager.GetString("Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer Array.
        /// </summary>
        public static string IntegerArray {
            get {
                return ResourceManager.GetString("IntegerArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Open.
        /// </summary>
        public static string IsAlwaysOpen {
            get {
                return ResourceManager.GetString("IsAlwaysOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half Day.
        /// </summary>
        public static string IsHalfDay {
            get {
                return ResourceManager.GetString("IsHalfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit.
        /// </summary>
        public static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Close.
        /// </summary>
        public static string LocalClose {
            get {
                return ResourceManager.GetString("LocalClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Open.
        /// </summary>
        public static string LocalOpen {
            get {
                return ResourceManager.GetString("LocalOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        public static string Long {
            get {
                return ResourceManager.GetString("Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maker Fee Rate.
        /// </summary>
        public static string MakerFeeRate {
            get {
                return ResourceManager.GetString("MakerFeeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Type.
        /// </summary>
        public static string MarketType {
            get {
                return ResourceManager.GetString("MarketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed.
        /// </summary>
        public static string Missed {
            get {
                return ResourceManager.GetString("Missed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missed Or Cancelled.
        /// </summary>
        public static string MissedOrCancelled {
            get {
                return ResourceManager.GetString("MissedOrCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Profit Loss.
        /// </summary>
        public static string NetProfitLoss {
            get {
                return ResourceManager.GetString("NetProfitLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Result.
        /// </summary>
        public static string NetResult {
            get {
                return ResourceManager.GetString("NetResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Auction.
        /// </summary>
        public static string OpeningAuction {
            get {
                return ResourceManager.GetString("OpeningAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Price.
        /// </summary>
        public static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Profit Amount.
        /// </summary>
        public static string OrderProfitAmount {
            get {
                return ResourceManager.GetString("OrderProfitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Quantity.
        /// </summary>
        public static string OrderQuantity {
            get {
                return ResourceManager.GetString("OrderQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Risk Amount.
        /// </summary>
        public static string OrderRiskAmount {
            get {
                return ResourceManager.GetString("OrderRiskAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL Order Type.
        /// </summary>
        public static string OrderTypeSL {
            get {
                return ResourceManager.GetString("OrderTypeSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP Order Type.
        /// </summary>
        public static string OrderTypeTP {
            get {
                return ResourceManager.GetString("OrderTypeTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Value.
        /// </summary>
        public static string OrderValue {
            get {
                return ResourceManager.GetString("OrderValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string Planned {
            get {
                return ResourceManager.GetString("Planned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Entry Price.
        /// </summary>
        public static string PlannedEntryPrice {
            get {
                return ResourceManager.GetString("PlannedEntryPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Position Value.
        /// </summary>
        public static string PlannedPositionValue {
            get {
                return ResourceManager.GetString("PlannedPositionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Profit.
        /// </summary>
        public static string PlannedProfit {
            get {
                return ResourceManager.GetString("PlannedProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Risk Amount.
        /// </summary>
        public static string PlannedRiskAmount {
            get {
                return ResourceManager.GetString("PlannedRiskAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned Risk Reward Ratio.
        /// </summary>
        public static string PlannedRiskRewardRatio {
            get {
                return ResourceManager.GetString("PlannedRiskRewardRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned SL.
        /// </summary>
        public static string PlannedSL {
            get {
                return ResourceManager.GetString("PlannedSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned TP.
        /// </summary>
        public static string PlannedTP {
            get {
                return ResourceManager.GetString("PlannedTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Market.
        /// </summary>
        public static string PreMarket {
            get {
                return ResourceManager.GetString("PreMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Half Year.
        /// </summary>
        public static string PreviousHalfYear {
            get {
                return ResourceManager.GetString("PreviousHalfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Month.
        /// </summary>
        public static string PreviousMonth {
            get {
                return ResourceManager.GetString("PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Quarter.
        /// </summary>
        public static string PreviousQuarter {
            get {
                return ResourceManager.GetString("PreviousQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Week.
        /// </summary>
        public static string PreviousWeek {
            get {
                return ResourceManager.GetString("PreviousWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Year.
        /// </summary>
        public static string PreviousYear {
            get {
                return ResourceManager.GetString("PreviousYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Currency.
        /// </summary>
        public static string PriceCurrency {
            get {
                return ResourceManager.GetString("PriceCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Currency.
        /// </summary>
        public static string PriceCurrencyId {
            get {
                return ResourceManager.GetString("PriceCurrencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realized Profit Loss.
        /// </summary>
        public static string RealizedProfitLoss {
            get {
                return ResourceManager.GetString("RealizedProfitLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realized R.
        /// </summary>
        public static string RealizedR {
            get {
                return ResourceManager.GetString("RealizedR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realized Risk Amount.
        /// </summary>
        public static string RealizedRiskAmount {
            get {
                return ResourceManager.GetString("RealizedRiskAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        public static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Trading Hours.
        /// </summary>
        public static string RegularTradingHours {
            get {
                return ResourceManager.GetString("RegularTradingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Open Position Value.
        /// </summary>
        public static string RemainingOpenPositionValue {
            get {
                return ResourceManager.GetString("RemainingOpenPositionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Open Quantity.
        /// </summary>
        public static string RemainingOpenQuantity {
            get {
                return ResourceManager.GetString("RemainingOpenQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Position Value.
        /// </summary>
        public static string RemainingPositionValue {
            get {
                return ResourceManager.GetString("RemainingPositionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Quantity.
        /// </summary>
        public static string RemainingQuantity {
            get {
                return ResourceManager.GetString("RemainingQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Currency.
        /// </summary>
        public static string RemoveCurrency {
            get {
                return ResourceManager.GetString("RemoveCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Entry Order.
        /// </summary>
        public static string RemoveEntryOrder {
            get {
                return ResourceManager.GetString("RemoveEntryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Exchange.
        /// </summary>
        public static string RemoveExchange {
            get {
                return ResourceManager.GetString("RemoveExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Holiday.
        /// </summary>
        public static string RemoveHoliday {
            get {
                return ResourceManager.GetString("RemoveHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Session.
        /// </summary>
        public static string RemoveSession {
            get {
                return ResourceManager.GetString("RemoveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Stop Loss Order.
        /// </summary>
        public static string RemoveStopLossOrder {
            get {
                return ResourceManager.GetString("RemoveStopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Symbol.
        /// </summary>
        public static string RemoveSymbol {
            get {
                return ResourceManager.GetString("RemoveSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Take Profit Order.
        /// </summary>
        public static string RemoveTakeProfitOrder {
            get {
                return ResourceManager.GetString("RemoveTakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Trade.
        /// </summary>
        public static string RemoveTrade {
            get {
                return ResourceManager.GetString("RemoveTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Trade Image.
        /// </summary>
        public static string RemoveTradeImage {
            get {
                return ResourceManager.GetString("RemoveTradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Trading Account.
        /// </summary>
        public static string RemoveTradingAccount {
            get {
                return ResourceManager.GetString("RemoveTradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Notes.
        /// </summary>
        public static string ReviewNotes {
            get {
                return ResourceManager.GetString("ReviewNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions List.
        /// </summary>
        public static string SessionsList {
            get {
                return ResourceManager.GetString("SessionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Type.
        /// </summary>
        public static string SessionType {
            get {
                return ResourceManager.GetString("SessionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Type.
        /// </summary>
        public static string SettingType {
            get {
                return ResourceManager.GetString("SettingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Notes.
        /// </summary>
        public static string SetupNotes {
            get {
                return ResourceManager.GetString("SetupNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        public static string Short {
            get {
                return ResourceManager.GetString("Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Limit.
        /// </summary>
        public static string StopLimit {
            get {
                return ResourceManager.GetString("StopLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Loss Order.
        /// </summary>
        public static string StopLossOrder {
            get {
                return ResourceManager.GetString("StopLossOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Loss Orders.
        /// </summary>
        public static string StopLossOrders {
            get {
                return ResourceManager.GetString("StopLossOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Loss Orders List.
        /// </summary>
        public static string StopLossOrdersList {
            get {
                return ResourceManager.GetString("StopLossOrdersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Market.
        /// </summary>
        public static string StopMarket {
            get {
                return ResourceManager.GetString("StopMarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String Array.
        /// </summary>
        public static string StringArray {
            get {
                return ResourceManager.GetString("StringArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday Open.
        /// </summary>
        public static string SundayOpen {
            get {
                return ResourceManager.GetString("SundayOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        public static string SymbolId {
            get {
                return ResourceManager.GetString("SymbolId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols List.
        /// </summary>
        public static string SymbolsList {
            get {
                return ResourceManager.GetString("SymbolsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Profit Order.
        /// </summary>
        public static string TakeProfitOrder {
            get {
                return ResourceManager.GetString("TakeProfitOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Profit Orders.
        /// </summary>
        public static string TakeProfitOrders {
            get {
                return ResourceManager.GetString("TakeProfitOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Profit Orders List.
        /// </summary>
        public static string TakeProfitOrdersList {
            get {
                return ResourceManager.GetString("TakeProfitOrdersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taker Fee Rate.
        /// </summary>
        public static string TakerFeeRate {
            get {
                return ResourceManager.GetString("TakerFeeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Half Year.
        /// </summary>
        public static string ThisHalfYear {
            get {
                return ResourceManager.GetString("ThisHalfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Quarter.
        /// </summary>
        public static string ThisQuarter {
            get {
                return ResourceManager.GetString("ThisQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Year.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker.
        /// </summary>
        public static string Ticker {
            get {
                return ResourceManager.GetString("Ticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker Full.
        /// </summary>
        public static string TickerFull {
            get {
                return ResourceManager.GetString("TickerFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string Timezone {
            get {
                return ResourceManager.GetString("Timezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Fees Calculated.
        /// </summary>
        public static string TotalFeesCalculated {
            get {
                return ResourceManager.GetString("TotalFeesCalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Fees Corrected.
        /// </summary>
        public static string TotalFeesCorrected {
            get {
                return ResourceManager.GetString("TotalFeesCorrected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        public static string Trade {
            get {
                return ResourceManager.GetString("Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Date Type.
        /// </summary>
        public static string TradeDateType {
            get {
                return ResourceManager.GetString("TradeDateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Direction.
        /// </summary>
        public static string TradeDirection {
            get {
                return ResourceManager.GetString("TradeDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade History.
        /// </summary>
        public static string TradeHistory {
            get {
                return ResourceManager.GetString("TradeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        public static string TradeId {
            get {
                return ResourceManager.GetString("TradeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Image.
        /// </summary>
        public static string TradeImage {
            get {
                return ResourceManager.GetString("TradeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Image Category.
        /// </summary>
        public static string TradeImageCategory {
            get {
                return ResourceManager.GetString("TradeImageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Images.
        /// </summary>
        public static string TradeImages {
            get {
                return ResourceManager.GetString("TradeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Images List.
        /// </summary>
        public static string TradeImagesList {
            get {
                return ResourceManager.GetString("TradeImagesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades.
        /// </summary>
        public static string Trades {
            get {
                return ResourceManager.GetString("Trades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades List.
        /// </summary>
        public static string TradesList {
            get {
                return ResourceManager.GetString("TradesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Status.
        /// </summary>
        public static string TradeStatus {
            get {
                return ResourceManager.GetString("TradeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Status Query.
        /// </summary>
        public static string TradeStatusQuery {
            get {
                return ResourceManager.GetString("TradeStatusQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Account.
        /// </summary>
        public static string TradingAccount {
            get {
                return ResourceManager.GetString("TradingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Account.
        /// </summary>
        public static string TradingAccountId {
            get {
                return ResourceManager.GetString("TradingAccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Accounts.
        /// </summary>
        public static string TradingAccounts {
            get {
                return ResourceManager.GetString("TradingAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading Accounts List.
        /// </summary>
        public static string TradingAccountsList {
            get {
                return ResourceManager.GetString("TradingAccountsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailing Stop.
        /// </summary>
        public static string TrailingStop {
            get {
                return ResourceManager.GetString("TrailingStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unallocated SL Quantity.
        /// </summary>
        public static string UnallocatedSLQuantity {
            get {
                return ResourceManager.GetString("UnallocatedSLQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unallocated Stop Loss Quantity.
        /// </summary>
        public static string UnallocatedStopLossQuantity {
            get {
                return ResourceManager.GetString("UnallocatedStopLossQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unallocated Take Profit Quantity.
        /// </summary>
        public static string UnallocatedTakeProfitQuantity {
            get {
                return ResourceManager.GetString("UnallocatedTakeProfitQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unallocated TP Quantity.
        /// </summary>
        public static string UnallocatedTPQuantity {
            get {
                return ResourceManager.GetString("UnallocatedTPQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated At.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Time.
        /// </summary>
        public static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
    }
}
