using TD.AppInfra.ViewModels;
using TD.Extensions;
using TD.Models;
using static TD.Extensions.EnumExtension;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Trades
{
    public partial class EntryOrderEditVM : AbstractCreateEditVM
    {
        private EntryOrder _entryOrder;
        public EntryOrder EntryOrder => _entryOrder;

        public EntryOrderEditVM(EntryOrder entryOrder)
        {
            _entryOrder = entryOrder;
            EntryOrderTypeValues = GetValues<EntryOrderType>();
            OnInitialized();
        }
        partial void OnInitialized();

        /// <summary>
        /// Gets the collection of available EntryOrderType enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<EntryOrderType>> EntryOrderTypeValues { get; }

        public int TradeId => _entryOrder.TradeId;

        public Trade Trade
        {
            get { return _entryOrder.Trade; }
            set
            {
                if (_entryOrder.Trade != value)
                {
                    _entryOrder.Trade = value;
                    RaisePropertyChanged(nameof(Trade));
                    ValidateProperty(_entryOrder, nameof(Trade));
                }
            }
        }

        public EntryOrderType OrderType
        {
            get { return _entryOrder.OrderType; }
            set
            {
                if (_entryOrder.OrderType != value)
                {
                    _entryOrder.OrderType = value;
                    RaisePropertyChanged(nameof(OrderType));
                    ValidateProperty(_entryOrder, nameof(OrderType));
                }
            }
        }

        public decimal OrderPrice
        {
            get { return _entryOrder.OrderPrice; }
            set
            {
                if (_entryOrder.OrderPrice != value)
                {
                    _entryOrder.OrderPrice = value;
                    RaisePropertyChanged(nameof(OrderPrice));
                    ValidateProperty(_entryOrder, nameof(OrderPrice));
                }
            }
        }

        public decimal? FilledPrice
        {
            get { return _entryOrder.FilledPrice; }
            set
            {
                if (_entryOrder.FilledPrice != value)
                {
                    _entryOrder.FilledPrice = value;
                    RaisePropertyChanged(nameof(FilledPrice));
                    ValidateProperty(_entryOrder, nameof(FilledPrice));
                }
            }
        }

        public decimal? OrderQuantity
        {
            get { return _entryOrder.OrderQuantity; }
            set
            {
                if (_entryOrder.OrderQuantity != value)
                {
                    _entryOrder.OrderQuantity = value;
                    RaisePropertyChanged(nameof(OrderQuantity));
                    ValidateProperty(_entryOrder, nameof(OrderQuantity));
                }
            }
        }

        public decimal? FilledQuantity
        {
            get { return _entryOrder.FilledQuantity; }
            set
            {
                if (_entryOrder.FilledQuantity != value)
                {
                    _entryOrder.FilledQuantity = value;
                    RaisePropertyChanged(nameof(FilledQuantity));
                    ValidateProperty(_entryOrder, nameof(FilledQuantity));
                }
            }
        }

        public decimal? OrderValue => _entryOrder.OrderValue;

        public decimal? FilledValue => _entryOrder.FilledValue;

        public DateTime? FilledTime
        {
            get { return _entryOrder.FilledTime; }
            set
            {
                if (_entryOrder.FilledTime != value)
                {
                    _entryOrder.FilledTime = value;
                    RaisePropertyChanged(nameof(FilledTime));
                    ValidateProperty(_entryOrder, nameof(FilledTime));
                }
            }
        }

        public string? Notes
        {
            get { return _entryOrder.Notes; }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && _entryOrder.Notes != value)
                {
                    _entryOrder.Notes = value;
                    RaisePropertyChanged(nameof(Notes));
                    ValidateProperty(_entryOrder, nameof(Notes));
                }
                else if (string.IsNullOrWhiteSpace(value))
                {
                    _entryOrder.Notes = null;
                    RaisePropertyChanged(nameof(Notes));
                    ValidateProperty(_entryOrder, nameof(Notes));
                }
            }
        }

        public bool ValidateModel()
        {
            return ValidateModel(_entryOrder);
        }
    }
}
