using TD.AppInfra.ViewModels;
using TD.Extensions;
using TD.Models;
using static TD.Extensions.EnumExtension;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Trades
{
    public partial class EntryOrderCreateVM : AbstractCreateEditVM
    {
        private EntryOrder _entryOrder;
        public EntryOrder EntryOrder => _entryOrder;

        public EntryOrderCreateVM()
        {
            _entryOrder = new EntryOrder();
            EntryOrderTypeValues = GetValues<EntryOrderType>();
            OnInitialized();
        }
        partial void OnInitialized();

        /// <summary>
        /// Gets the collection of available EntryOrderType enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<EntryOrderType>> EntryOrderTypeValues { get; }

        public int TradeId
        {
            get { return _entryOrder.TradeId; }
            set
            {
                if (_entryOrder.TradeId != value)
                {
                    _entryOrder.TradeId = value;
                    RaisePropertyChanged(nameof(TradeId));
                    ValidateProperty(_entryOrder, nameof(TradeId));
                }
            }
        }

        public Trade Trade
        {
            get { return _entryOrder.Trade; }
            set
            {
                if (_entryOrder.Trade != value)
                {
                    _entryOrder.Trade = value;
                    RaisePropertyChanged(nameof(Trade));
                    ValidateProperty(_entryOrder, nameof(Trade));
                }
            }
        }

        public EntryOrderType OrderType
        {
            get { return _entryOrder.OrderType; }
            set
            {
                if (_entryOrder.OrderType != value)
                {
                    _entryOrder.OrderType = value;
                    RaisePropertyChanged(nameof(OrderType));
                    ValidateProperty(_entryOrder, nameof(OrderType));
                }
            }
        }

        public decimal OrderPrice
        {
            get { return _entryOrder.OrderPrice; }
            set
            {
                if (_entryOrder.OrderPrice != value)
                {
                    _entryOrder.OrderPrice = value;
                    RaisePropertyChanged(nameof(OrderPrice));
                    ValidateProperty(_entryOrder, nameof(OrderPrice));
                }
            }
        }

        public decimal? OrderQuantity
        {
            get { return _entryOrder.OrderQuantity; }
            set
            {
                if (_entryOrder.OrderQuantity != value)
                {
                    _entryOrder.OrderQuantity = value;
                    RaisePropertyChanged(nameof(OrderQuantity));
                    ValidateProperty(_entryOrder, nameof(OrderQuantity));
                }
            }
        }

        public decimal? OrderValue
        {
            get { return _entryOrder.OrderValue; }
            set
            {
                if (_entryOrder.OrderValue != value)
                {
                    _entryOrder.OrderValue = value;
                    RaisePropertyChanged(nameof(OrderValue));
                    ValidateProperty(_entryOrder, nameof(OrderValue));
                }
            }
        }

        public string? Notes
        {
            get { return _entryOrder.Notes; }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && _entryOrder.Notes != value)
                {
                    _entryOrder.Notes = value;
                    RaisePropertyChanged(nameof(Notes));
                    ValidateProperty(_entryOrder, nameof(Notes));
                }
                else if (string.IsNullOrWhiteSpace(value))
                {
                    _entryOrder.Notes = null;
                    RaisePropertyChanged(nameof(Notes));
                    ValidateProperty(_entryOrder, nameof(Notes));
                }
            }
        }

        public bool ValidateModel()
        {
            return ValidateModel(_entryOrder);
        }
    }
}
