using TD.AppInfra.ViewModels;
using TD.Extensions;
using TD.Models;
using static TD.Extensions.EnumExtension;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Trades
{
    public partial class StopLossOrderCreateVM : AbstractCreateEditVM
    {
        private StopLossOrder _stopLossOrder;
        public StopLossOrder StopLossOrder => _stopLossOrder;

        public StopLossOrderCreateVM()
        {
            _stopLossOrder = new StopLossOrder();
            ExitOrderTypeValues = GetValues<ExitOrderType>();
            OnInitialized();
        }
        partial void OnInitialized();

        /// <summary>
        /// Gets the collection of available ExitOrderType enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<ExitOrderType>> ExitOrderTypeValues { get; }

        public int TradeId
        {
            get { return _stopLossOrder.TradeId; }
            set
            {
                if (_stopLossOrder.TradeId != value)
                {
                    _stopLossOrder.TradeId = value;
                    RaisePropertyChanged(nameof(TradeId));
                    ValidateProperty(_stopLossOrder, nameof(TradeId));
                }
            }
        }

        public Trade Trade
        {
            get { return _stopLossOrder.Trade; }
            set
            {
                if (_stopLossOrder.Trade != value)
                {
                    _stopLossOrder.Trade = value;
                    RaisePropertyChanged(nameof(Trade));
                    ValidateProperty(_stopLossOrder, nameof(Trade));
                }
            }
        }

        public ExitOrderType OrderType
        {
            get { return _stopLossOrder.OrderType; }
            set
            {
                if (_stopLossOrder.OrderType != value)
                {
                    _stopLossOrder.OrderType = value;
                    RaisePropertyChanged(nameof(OrderType));
                    ValidateProperty(_stopLossOrder, nameof(OrderType));
                }
            }
        }

        public decimal OrderPrice
        {
            get { return _stopLossOrder.OrderPrice; }
            set
            {
                if (_stopLossOrder.OrderPrice != value)
                {
                    _stopLossOrder.OrderPrice = value;
                    RaisePropertyChanged(nameof(OrderPrice));
                    ValidateProperty(_stopLossOrder, nameof(OrderPrice));
                }
            }
        }

        public decimal? OrderQuantity
        {
            get { return _stopLossOrder.OrderQuantity; }
            set
            {
                if (_stopLossOrder.OrderQuantity != value)
                {
                    _stopLossOrder.OrderQuantity = value;
                    RaisePropertyChanged(nameof(OrderQuantity));
                    ValidateProperty(_stopLossOrder, nameof(OrderQuantity));
                }
            }
        }

        public decimal? OrderValue
        {
            get { return _stopLossOrder.OrderValue; }
            set
            {
                if (_stopLossOrder.OrderValue != value)
                {
                    _stopLossOrder.OrderValue = value;
                    RaisePropertyChanged(nameof(OrderValue));
                    ValidateProperty(_stopLossOrder, nameof(OrderValue));
                }
            }
        }

        public string? Notes
        {
            get { return _stopLossOrder.Notes; }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && _stopLossOrder.Notes != value)
                {
                    _stopLossOrder.Notes = value;
                    RaisePropertyChanged(nameof(Notes));
                    ValidateProperty(_stopLossOrder, nameof(Notes));
                }
                else if (string.IsNullOrWhiteSpace(value))
                {
                    _stopLossOrder.Notes = null;
                    RaisePropertyChanged(nameof(Notes));
                    ValidateProperty(_stopLossOrder, nameof(Notes));
                }
            }
        }

        public bool ValidateModel()
        {
            return ValidateModel(_stopLossOrder);
        }
    }
}
