using System.Collections.ObjectModel;
using TD.AppInfra.Services;
using TD.AppInfra.ViewModels;
using TD.AppInfra.ViewModels.Trades;
using TD.Extensions;
using TD.Helpers;
using TD.Models;
using TD.RepositoryContracts;
using TD.WPF.Commands.Trades;
using TD.WPF.Services;
using static TD.Extensions.EnumExtension;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Trades
{
    public partial class TradeListVM : AbstractCollectionVM<Trade>
    {
        public TradeListVM(ITradeRepository tradeRepository, IWindowDialogService windowDialogService,
                           ISymbolLookupService symbolLookupService, ITradingAccountLookupService tradingAccountLookupService)
        {
            TradeRepository = tradeRepository;
            Trades = new ObservableCollection<Trade>();
            QueryVM = new TradeQueryParametersVM();
            QueryVM.PropertyChanged += OnPropertyChanged;
            PropertyChanged += OnPropertyChanged;

            TradeDirectionValues = GetValues<TradeDirection>();
            TradeStatusValues = GetValues<TradeStatus>();
            MarketTypeValues = GetValues<MarketType>();
            TradeCreateCommand = new TradeCreateCommand(this, windowDialogService, symbolLookupService, tradingAccountLookupService);
            TradeDeleteCommand = new TradeDeleteCommand(this);
            TradeDetailCommand = new TradeDetailCommand(this, windowDialogService);
            TradeEditCommand = new TradeEditCommand(this, windowDialogService);
            TradesLoadCommand = new TradesLoadCommand(this);
            TradesNextPageCommand = new TradesNextPageCommand(this);
            TradesPrevPageCommand = new TradesPrevPageCommand(this);
        }

        public ITradeRepository TradeRepository { get; }
        public ObservableCollection<Trade> Trades { get; }

        /// <summary>
        /// Gets the collection of available TradeDirection enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<TradeDirection>> TradeDirectionValues { get; }

        /// <summary>
        /// Gets the collection of available TradeStatus enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<TradeStatus>> TradeStatusValues { get; }

        /// <summary>
        /// Gets the collection of available MarketType enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<MarketType>> MarketTypeValues { get; }

        public TradeCreateCommand TradeCreateCommand { get; }
        public TradeDeleteCommand TradeDeleteCommand { get; }
        public TradeDetailCommand TradeDetailCommand { get; }
        public TradeEditCommand TradeEditCommand { get; }
        public TradesLoadCommand TradesLoadCommand { get; }
        public TradesNextPageCommand TradesNextPageCommand { get; }
        public TradesPrevPageCommand TradesPrevPageCommand { get; }

        public TradeQueryParametersVM QueryVM { get; }

        public async Task LoadTradesAsync()
        {
            await LoadTradesAsync(QueryVM);
        }

        protected async Task LoadTradesAsync(TradeQueryParametersVM queryVM)
        {
            if (LoadTradesInProgress)
                return;

            LoadTradesInProgress = true;
            TradesLoadCommand.RaiseCanExecuteChanged();
            TradesPrevPageCommand.RaiseCanExecuteChanged();
            TradesNextPageCommand.RaiseCanExecuteChanged();

            var items = await TradeRepository.GetPagedAsync(queryVM.Parameters);
            RaisePropertyChanged(nameof(QueryVM));
            ReplaceCollection(Trades, items);

            LoadTradesInProgress = false;
            TradesLoadCommand.RaiseCanExecuteChanged();
            TradesPrevPageCommand.RaiseCanExecuteChanged();
            TradesNextPageCommand.RaiseCanExecuteChanged();
            OnTradesLoaded();
        }
        public bool LoadTradesInProgress { get; private set; } = false;
        protected virtual void OnTradesLoaded() { /* For override in derived classes */ }

        public async Task SaveTradeAsync(Trade trade)
        {
            if (trade.Id <= 0)
                trade.Id = await TradeRepository.CreateAsync(trade);
            else
                await TradeRepository.UpdateAsync(trade);
        }

        public Trade? SelectedTrade
        {
            get { return SelectedItem; }
            set
            {
                SelectedItem = value;
                TradeEditCommand.RaiseCanExecuteChanged();
                TradeDeleteCommand.RaiseCanExecuteChanged();
                TradeDetailCommand.RaiseCanExecuteChanged();
                RaisePropertyChanged(nameof(SelectedTrade));
            }
        }

        protected virtual void OnPropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
        {
            if (e.PropertyName == nameof(QueryVM.PageSize))
            {
                TradesLoadCommand.RaiseCanExecuteChanged();
                TradesPrevPageCommand.RaiseCanExecuteChanged();
                TradesNextPageCommand.RaiseCanExecuteChanged();
            }
        }
    }
}
