using TD.AppInfra.ViewModels;
using TD.Extensions;
using TD.Models;
using static TD.Extensions.EnumExtension;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Trades
{
    public partial class TradeEditVM : AbstractCreateEditVM
    {
        private Trade _trade;
        public Trade Trade => _trade;

        public TradeEditVM(Trade trade)
        {
            _trade = trade;
            TradeDirectionValues = GetValues<TradeDirection>();
            TradeStatusValues = GetValues<TradeStatus>();
            MarketTypeValues = GetValues<MarketType>();
            OnInitialized();
        }
        partial void OnInitialized();

        /// <summary>
        /// Gets the collection of available TradeDirection enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<TradeDirection>> TradeDirectionValues { get; }

        /// <summary>
        /// Gets the collection of available TradeStatus enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<TradeStatus>> TradeStatusValues { get; }

        /// <summary>
        /// Gets the collection of available MarketType enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<MarketType>> MarketTypeValues { get; }

        public int TradingAccountId => _trade.TradingAccountId;

        public TradingAccount TradingAccount => _trade.TradingAccount;

        public int SymbolId => _trade.SymbolId;

        public Symbol Symbol => _trade.Symbol;

        public DateTime? EntryTime
        {
            get { return _trade.EntryTime; }
            set
            {
                if (_trade.EntryTime != value)
                {
                    _trade.EntryTime = value;
                    RaisePropertyChanged(nameof(EntryTime));
                    ValidateProperty(_trade, nameof(EntryTime));
                }
            }
        }

        public DateTime? ExitTime
        {
            get { return _trade.ExitTime; }
            set
            {
                if (_trade.ExitTime != value)
                {
                    _trade.ExitTime = value;
                    RaisePropertyChanged(nameof(ExitTime));
                    ValidateProperty(_trade, nameof(ExitTime));
                }
            }
        }

        public TradeDirection TradeDirection => _trade.TradeDirection;

        public TradeStatus TradeStatus
        {
            get { return _trade.TradeStatus; }
            set
            {
                if (_trade.TradeStatus != value)
                {
                    _trade.TradeStatus = value;
                    RaisePropertyChanged(nameof(TradeStatus));
                    ValidateProperty(_trade, nameof(TradeStatus));
                }
            }
        }

        public decimal? PlannedEntryPrice => _trade.PlannedEntryPrice;

        public decimal? ExecutedEntryPrice => _trade.ExecutedEntryPrice;

        public decimal? PlannedPositionValue => _trade.PlannedPositionValue;

        public decimal? ExecutedPositionValue => _trade.ExecutedPositionValue;

        public decimal? OrderQuantity => _trade.OrderQuantity;

        public decimal? FilledQuantity => _trade.FilledQuantity;

        public decimal? PlannedProfit => _trade.PlannedProfit;

        public decimal? PlannedTP => _trade.PlannedTP;

        public decimal? ExecutedTP => _trade.ExecutedTP;

        public decimal? PlannedSL => _trade.PlannedSL;

        public decimal? ExecutedSL => _trade.ExecutedSL;

        public decimal? PlannedRiskRewardRatio => _trade.PlannedRiskRewardRatio;

        public decimal? RealizedProfitLoss => _trade.RealizedProfitLoss;

        public decimal? NetProfitLoss => _trade.NetProfitLoss;

        public decimal? TotalFeesCalculated => _trade.TotalFeesCalculated;

        public decimal? TotalFeesCorrected
        {
            get { return _trade.TotalFeesCorrected; }
            set
            {
                if (_trade.TotalFeesCorrected != value)
                {
                    _trade.TotalFeesCorrected = value;
                    RaisePropertyChanged(nameof(TotalFeesCorrected));
                    ValidateProperty(_trade, nameof(TotalFeesCorrected));
                }
            }
        }

        public decimal? FundingFeeTotal
        {
            get { return _trade.FundingFeeTotal; }
            set
            {
                if (_trade.FundingFeeTotal != value)
                {
                    _trade.FundingFeeTotal = value;
                    RaisePropertyChanged(nameof(FundingFeeTotal));
                    ValidateProperty(_trade, nameof(FundingFeeTotal));
                }
            }
        }

        public string? Tags
        {
            get { return _trade.Tags; }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && _trade.Tags != value)
                {
                    _trade.Tags = value;
                    RaisePropertyChanged(nameof(Tags));
                    ValidateProperty(_trade, nameof(Tags));
                }
                else if (string.IsNullOrWhiteSpace(value))
                {
                    _trade.Tags = null;
                    RaisePropertyChanged(nameof(Tags));
                    ValidateProperty(_trade, nameof(Tags));
                }
            }
        }

        public string? SetupNotes => _trade.SetupNotes;

        public string? ReviewNotes
        {
            get { return _trade.ReviewNotes; }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && _trade.ReviewNotes != value)
                {
                    _trade.ReviewNotes = value;
                    RaisePropertyChanged(nameof(ReviewNotes));
                    ValidateProperty(_trade, nameof(ReviewNotes));
                }
                else if (string.IsNullOrWhiteSpace(value))
                {
                    _trade.ReviewNotes = null;
                    RaisePropertyChanged(nameof(ReviewNotes));
                    ValidateProperty(_trade, nameof(ReviewNotes));
                }
            }
        }

        public bool ValidateModel()
        {
            return ValidateModel(_trade);
        }
    }
}
