using System.Collections.ObjectModel;
using TD.AppInfra.Services;
using TD.AppInfra.ViewModels;
using TD.Extensions;
using TD.Models;
using static TD.Extensions.EnumExtension;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Trades
{
    public partial class TradeCreateVM : AbstractCreateEditVM
    {
        private readonly ISymbolLookupService _symbolLookupService;
        private readonly ITradingAccountLookupService _tradingAccountLookupService;
        private Trade _trade;
        public Trade Trade => _trade;

        public TradeCreateVM(ISymbolLookupService symbolLookupService, ITradingAccountLookupService tradingAccountLookupService)
        {
            _symbolLookupService = symbolLookupService;
            Symbols = new ObservableCollection<Symbol>();

            _tradingAccountLookupService = tradingAccountLookupService;
            TradingAccounts = new ObservableCollection<TradingAccount>();

            _trade = new Trade();
            TradeDirectionValues = GetValues<TradeDirection>();
            TradeStatusValues = GetValues<TradeStatus>();
            MarketTypeValues = GetValues<MarketType>();
            OnInitialized();
        }
        partial void OnInitialized();

        public ObservableCollection<Symbol> Symbols { get; }

        public async Task LoadSymbolsAsync()
        {
            var items = await _symbolLookupService.GetSymbolsAsync(isActive: true);
            Symbols.Clear();
            foreach (var item in items)
            {
                Symbols.Add(item);
            }
        }

        public ObservableCollection<TradingAccount> TradingAccounts { get; }

        public async Task LoadTradingAccountsAsync()
        {
            var items = await _tradingAccountLookupService.GetTradingAccountsAsync(isActive: true);
            TradingAccounts.Clear();
            foreach (var item in items)
            {
                TradingAccounts.Add(item);
            }
        }

        /// <summary>
        /// Gets the collection of available TradeDirection enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<TradeDirection>> TradeDirectionValues { get; }

        /// <summary>
        /// Gets the collection of available TradeStatus enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<TradeStatus>> TradeStatusValues { get; }

        /// <summary>
        /// Gets the collection of available MarketType enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<MarketType>> MarketTypeValues { get; }

        public int TradingAccountId
        {
            get { return _trade.TradingAccountId; }
            set
            {
                if (_trade.TradingAccountId != value)
                {
                    _trade.TradingAccountId = value;
                    RaisePropertyChanged(nameof(TradingAccountId));
                    ValidateProperty(_trade, nameof(TradingAccountId));
                }
            }
        }

        public TradingAccount TradingAccount
        {
            get { return _trade.TradingAccount; }
            set
            {
                if (_trade.TradingAccount != value)
                {
                    _trade.TradingAccount = value;
                    RaisePropertyChanged(nameof(TradingAccount));
                    ValidateProperty(_trade, nameof(TradingAccount));
                }
            }
        }

        public int SymbolId
        {
            get { return _trade.SymbolId; }
            set
            {
                if (_trade.SymbolId != value)
                {
                    _trade.SymbolId = value;
                    RaisePropertyChanged(nameof(SymbolId));
                    ValidateProperty(_trade, nameof(SymbolId));
                }
            }
        }

        public Symbol Symbol
        {
            get { return _trade.Symbol; }
            set
            {
                if (_trade.Symbol != value)
                {
                    _trade.Symbol = value;
                    RaisePropertyChanged(nameof(Symbol));
                    ValidateProperty(_trade, nameof(Symbol));
                }
            }
        }

        public DateTime? EntryTime
        {
            get { return _trade.EntryTime; }
            set
            {
                if (_trade.EntryTime != value)
                {
                    _trade.EntryTime = value;
                    RaisePropertyChanged(nameof(EntryTime));
                    ValidateProperty(_trade, nameof(EntryTime));
                }
            }
        }

        public DateTime? ExitTime
        {
            get { return _trade.ExitTime; }
            set
            {
                if (_trade.ExitTime != value)
                {
                    _trade.ExitTime = value;
                    RaisePropertyChanged(nameof(ExitTime));
                    ValidateProperty(_trade, nameof(ExitTime));
                }
            }
        }

        public TradeDirection TradeDirection
        {
            get { return _trade.TradeDirection; }
            set
            {
                if (_trade.TradeDirection != value)
                {
                    _trade.TradeDirection = value;
                    RaisePropertyChanged(nameof(TradeDirection));
                    ValidateProperty(_trade, nameof(TradeDirection));
                }
            }
        }

        public TradeStatus TradeStatus
        {
            get { return _trade.TradeStatus; }
            set
            {
                if (_trade.TradeStatus != value)
                {
                    _trade.TradeStatus = value;
                    RaisePropertyChanged(nameof(TradeStatus));
                    ValidateProperty(_trade, nameof(TradeStatus));
                }
            }
        }

        public MarketType MarketType => _trade.MarketType;

        public decimal? PlannedEntryPrice
        {
            get { return _trade.PlannedEntryPrice; }
            set
            {
                if (_trade.PlannedEntryPrice != value)
                {
                    _trade.PlannedEntryPrice = value;
                    RaisePropertyChanged(nameof(PlannedEntryPrice));
                    ValidateProperty(_trade, nameof(PlannedEntryPrice));
                }
            }
        }

        public decimal? PlannedPositionValue
        {
            get { return _trade.PlannedPositionValue; }
            set
            {
                if (_trade.PlannedPositionValue != value)
                {
                    _trade.PlannedPositionValue = value;
                    RaisePropertyChanged(nameof(PlannedPositionValue));
                    ValidateProperty(_trade, nameof(PlannedPositionValue));
                }
            }
        }

        public decimal? OrderQuantity
        {
            get { return _trade.OrderQuantity; }
            set
            {
                if (_trade.OrderQuantity != value)
                {
                    _trade.OrderQuantity = value;
                    RaisePropertyChanged(nameof(OrderQuantity));
                    ValidateProperty(_trade, nameof(OrderQuantity));
                }
            }
        }

        public decimal? PlannedProfit => _trade.PlannedProfit;

        public decimal? PlannedTP
        {
            get { return _trade.PlannedTP; }
            set
            {
                if (_trade.PlannedTP != value)
                {
                    _trade.PlannedTP = value;
                    RaisePropertyChanged(nameof(PlannedTP));
                    ValidateProperty(_trade, nameof(PlannedTP));
                }
            }
        }

        public decimal? PlannedSL
        {
            get { return _trade.PlannedSL; }
            set
            {
                if (_trade.PlannedSL != value)
                {
                    _trade.PlannedSL = value;
                    RaisePropertyChanged(nameof(PlannedSL));
                    ValidateProperty(_trade, nameof(PlannedSL));
                }
            }
        }

        public decimal? PlannedRiskAmount => _trade.PlannedRiskAmount;

        public decimal? PlannedRiskRewardRatio => _trade.PlannedRiskRewardRatio;

        public string? Tags
        {
            get { return _trade.Tags; }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && _trade.Tags != value)
                {
                    _trade.Tags = value;
                    RaisePropertyChanged(nameof(Tags));
                    ValidateProperty(_trade, nameof(Tags));
                }
                else if (string.IsNullOrWhiteSpace(value))
                {
                    _trade.Tags = null;
                    RaisePropertyChanged(nameof(Tags));
                    ValidateProperty(_trade, nameof(Tags));
                }
            }
        }

        public string? SetupNotes
        {
            get { return _trade.SetupNotes; }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && _trade.SetupNotes != value)
                {
                    _trade.SetupNotes = value;
                    RaisePropertyChanged(nameof(SetupNotes));
                    ValidateProperty(_trade, nameof(SetupNotes));
                }
                else if (string.IsNullOrWhiteSpace(value))
                {
                    _trade.SetupNotes = null;
                    RaisePropertyChanged(nameof(SetupNotes));
                    ValidateProperty(_trade, nameof(SetupNotes));
                }
            }
        }

        public bool ValidateModel()
        {
            return ValidateModel(_trade);
        }
    }
}
