using System.Windows;
using TD.AppInfra.Commands;
using TD.i18n;
using TD.WPF.ViewModels;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.Commands.Exchanges
{
    public partial class ExchangeDeleteCommand : AbstractCommand
    {
        protected readonly AbstractDiaryVM _viewModel;

        public ExchangeDeleteCommand(AbstractDiaryVM viewModel)
        {
            _viewModel = viewModel;
        }

        public override bool CanExecute(object? parameter)
        {
            var exchange = _viewModel.SelectedExchange;
            if (exchange is null)
                return false;

            if (exchange.Id < 1)
                return false;


            var result = _viewModel.ExchangeRepository
                                   .CanDeleteAsync(exchange.Id)
                                   .GetAwaiter()
                                   .GetResult();
            return result;
        }

        public override async void Execute(object? parameter)
        {
            var exchange = _viewModel.SelectedExchange;
            if (exchange is null)
                return;

            if (exchange.Id < 1)
                return;

            var result = MessageBox.Show(
                MessageStrings.AreYouSureToDelete,
                CommonStrings.AppTitle,
                MessageBoxButton.YesNo,
                MessageBoxImage.Question);

            if (result != MessageBoxResult.Yes)
                return;

            bool deleted = await _viewModel.ExchangeRepository.DeleteAsync(exchange.Id);
            if (!deleted)
                return;

            _viewModel.SelectedExchange = null;
            _viewModel.Exchanges.Remove(exchange);
            await _viewModel.LoadExchangesAsync();
        }
    }
}