using System.Windows;
using TD.AppInfra.Commands;
using TD.AppInfra.Services;
using TD.i18n;
using TD.WPF.Services;
using TD.WPF.ViewModels;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.Commands.Exchanges
{
    public partial class ExchangeCreateCommand : AbstractCommand
    {
        protected readonly AbstractDiaryVM _viewModel;
        private readonly IWindowDialogService _windowDialogService;
        private readonly ICurrencyLookupService _currencyLookupService;

        public ExchangeCreateCommand(AbstractDiaryVM viewModel, IWindowDialogService windowDialogService,
                                     ICurrencyLookupService currencyLookupService)
        {
            _viewModel = viewModel;
            _windowDialogService = windowDialogService;
            _currencyLookupService = currencyLookupService;
        }

        public override async void Execute(object? parameter)
        {
            if (parameter is not Window owner)
                return;

            try
            {
                var dialogResult = _windowDialogService.ShowExchangeCreateDialog(owner, _currencyLookupService);

                if (dialogResult.IsConfirmed && dialogResult.Exchange is not null)
                {
                    var exchange = dialogResult.Exchange;
                    await _viewModel.SaveExchangeAsync(exchange);
                    await _viewModel.LoadExchangesAsync();

                    _viewModel.SelectedExchange = _viewModel.Exchanges.FirstOrDefault(x => x.Id == exchange.Id);
                }
            }
            catch (Exception ex)
            {
                string innerExceptionMsg = ex.InnerException != null ? $"\n{ex.InnerException.Message}" : "";
                MessageBox.Show($"{MessageStrings.SaveOperationFailed}\n{ex.Message}{innerExceptionMsg}",
                    CommonStrings.AppTitle,
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }
    }
}