using System.Windows;
using TD.AppInfra.Commands;
using TD.i18n;
using TD.WPF.ViewModels;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.Commands.Maintenance
{
    public partial class CurrencyDeleteCommand : AbstractCommand
    {
        protected readonly AbstractDiaryVM _viewModel;

        public CurrencyDeleteCommand(AbstractDiaryVM viewModel)
        {
            _viewModel = viewModel;
        }

        public override bool CanExecute(object? parameter)
        {
            var currency = _viewModel.SelectedCurrency;
            if (currency is null)
                return false;

            if (currency.Id < 1)
                return false;


            var result = _viewModel.CurrencyRepository
                                   .CanDeleteAsync(currency.Id)
                                   .GetAwaiter()
                                   .GetResult();
            return result;
        }

        public override async void Execute(object? parameter)
        {
            var currency = _viewModel.SelectedCurrency;
            if (currency is null)
                return;

            if (currency.Id < 1)
                return;

            var result = MessageBox.Show(
                MessageStrings.AreYouSureToDelete,
                CommonStrings.AppTitle,
                MessageBoxButton.YesNo,
                MessageBoxImage.Question);

            if (result != MessageBoxResult.Yes)
                return;

            bool deleted = await _viewModel.CurrencyRepository.DeleteAsync(currency.Id);
            if (!deleted)
                return;

            _viewModel.SelectedCurrency = null;
            _viewModel.Currencies.Remove(currency);
            await _viewModel.LoadCurrenciesAsync();
        }
    }
}