using System.Windows;
using TD.AppInfra.Commands;
using TD.AppInfra.ViewModels;
using TD.i18n;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.Commands.Maintenance
{
    public partial class SymbolDeleteCommand : AbstractCommand
    {
        protected readonly ISymbolCreationContext _viewModel;

        public SymbolDeleteCommand(ISymbolCreationContext viewModel)
        {
            _viewModel = viewModel;
        }

        public override bool CanExecute(object? parameter)
        {
            var symbol = _viewModel.SelectedSymbol;
            if (symbol is null)
                return false;

            if (symbol.Id < 1)
                return false;


            var result = _viewModel.SymbolRepository
                                   .CanDeleteAsync(symbol.Id)
                                   .GetAwaiter()
                                   .GetResult();
            return result;
        }

        public override async void Execute(object? parameter)
        {
            var symbol = _viewModel.SelectedSymbol;
            if (symbol is null)
                return;

            if (symbol.Id < 1)
                return;

            var result = MessageBox.Show(
                MessageStrings.AreYouSureToDelete,
                CommonStrings.AppTitle,
                MessageBoxButton.YesNo,
                MessageBoxImage.Question);

            if (result != MessageBoxResult.Yes)
                return;

            bool deleted = await _viewModel.SymbolRepository.DeleteAsync(symbol.Id);
            if (!deleted)
                return;

            _viewModel.SelectedSymbol = null;
            _viewModel.Symbols.Remove(symbol);
            await _viewModel.LoadSymbolsAsync();
        }
    }
}