using System.Windows;
using TD.AppInfra.Commands;
using TD.AppInfra.ViewModels;
using TD.i18n;
using TD.WPF.Services;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.Commands.Maintenance
{
    public partial class SymbolEditCommand : AbstractCommand
    {
        protected readonly ISymbolCreationContext _viewModel;
        private readonly IWindowDialogService _windowDialogService;

        public SymbolEditCommand(ISymbolCreationContext viewModel, IWindowDialogService windowDialogService)
        {
            _viewModel = viewModel;
            _windowDialogService = windowDialogService;
        }

        public override bool CanExecute(object? parameter)
        {
            return _viewModel.SelectedSymbol is not null;
        }

        public override async void Execute(object? parameter)
        {
            if (_viewModel.SelectedSymbol is null)
                return;

            if (parameter is not Window owner)
                return;

            var symbol = _viewModel.SelectedSymbol;

            try
            {
                var dialogResult = _windowDialogService.ShowSymbolEditDialog(owner, _viewModel.SelectedSymbol);
                if (dialogResult.IsConfirmed && dialogResult.IsDirty)
                {
                    await _viewModel.SaveSymbolAsync(symbol);
                    await _viewModel.LoadSymbolsAsync();
                }
                else if (dialogResult.IsDirty)
                {
                    await _viewModel.LoadSymbolsAsync();
                }

                _viewModel.SelectedSymbol = _viewModel.Symbols.FirstOrDefault(x => x.Id == symbol.Id);
            }
            catch (Exception ex)
            {
                string innerExceptionMsg = ex.InnerException != null ? $"\n{ex.InnerException.Message}" : "";
                MessageBox.Show($"{MessageStrings.SaveOperationFailed}\n{ex.Message}{innerExceptionMsg}",
                    CommonStrings.AppTitle,
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
        }
    }
}