using System.Windows;
using TD.AppInfra.Commands;
using TD.i18n;
using TD.WPF.ViewModels;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.Commands.Maintenance
{
    public partial class TradingAccountDeleteCommand : AbstractCommand
    {
        protected readonly AbstractDiaryVM _viewModel;

        public TradingAccountDeleteCommand(AbstractDiaryVM viewModel)
        {
            _viewModel = viewModel;
        }

        public override bool CanExecute(object? parameter)
        {
            var tradingAccount = _viewModel.SelectedTradingAccount;
            if (tradingAccount is null)
                return false;

            if (tradingAccount.Id < 1)
                return false;


            var result = _viewModel.TradingAccountRepository
                                   .CanDeleteAsync(tradingAccount.Id)
                                   .GetAwaiter()
                                   .GetResult();
            return result;
        }

        public override async void Execute(object? parameter)
        {
            var tradingAccount = _viewModel.SelectedTradingAccount;
            if (tradingAccount is null)
                return;

            if (tradingAccount.Id < 1)
                return;

            var result = MessageBox.Show(
                MessageStrings.AreYouSureToDelete,
                CommonStrings.AppTitle,
                MessageBoxButton.YesNo,
                MessageBoxImage.Question);

            if (result != MessageBoxResult.Yes)
                return;

            bool deleted = await _viewModel.TradingAccountRepository.DeleteAsync(tradingAccount.Id);
            if (!deleted)
                return;

            _viewModel.SelectedTradingAccount = null;
            _viewModel.TradingAccounts.Remove(tradingAccount);
            await _viewModel.LoadTradingAccountsAsync();
        }
    }
}