using TD.AppInfra.ViewModels;
using TD.Models;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Exchanges
{
    public partial class ExchangeEditVM : AbstractCreateEditVM
    {
        private Exchange _exchange;
        public Exchange Exchange => _exchange;

        public ExchangeEditVM(Exchange exchange)
        {
            _exchange = exchange;
            OnInitialized();
        }
        partial void OnInitialized();

        public string ExchangeName
        {
            get { return _exchange.ExchangeName; }
            set
            {
                if (_exchange.ExchangeName != value)
                {
                    _exchange.ExchangeName = value;
                    RaisePropertyChanged(nameof(ExchangeName));
                    ValidateProperty(_exchange, nameof(ExchangeName));
                }
            }
        }

        public string ExchangeCode => _exchange.ExchangeCode;

        public string CountryCode
        {
            get { return _exchange.CountryCode; }
            set
            {
                if (_exchange.CountryCode != value)
                {
                    _exchange.CountryCode = value;
                    RaisePropertyChanged(nameof(CountryCode));
                    ValidateProperty(_exchange, nameof(CountryCode));
                }
            }
        }

        public int DefaultCurrencyId => _exchange.DefaultCurrencyId;

        public Currency DefaultCurrency
        {
            get { return _exchange.DefaultCurrency; }
            set
            {
                if (_exchange.DefaultCurrency != value)
                {
                    _exchange.DefaultCurrency = value;
                    RaisePropertyChanged(nameof(DefaultCurrency));
                    ValidateProperty(_exchange, nameof(DefaultCurrency));
                }
            }
        }

        public string Timezone
        {
            get { return _exchange.Timezone; }
            set
            {
                if (_exchange.Timezone != value)
                {
                    _exchange.Timezone = value;
                    RaisePropertyChanged(nameof(Timezone));
                    ValidateProperty(_exchange, nameof(Timezone));
                }
            }
        }

        public bool IsAlwaysOpen
        {
            get { return _exchange.IsAlwaysOpen; }
            set
            {
                if (_exchange.IsAlwaysOpen != value)
                {
                    _exchange.IsAlwaysOpen = value;
                    RaisePropertyChanged(nameof(IsAlwaysOpen));
                    ValidateProperty(_exchange, nameof(IsAlwaysOpen));
                }
            }
        }

        public int DisplayOrder
        {
            get { return _exchange.DisplayOrder; }
            set
            {
                if (_exchange.DisplayOrder != value)
                {
                    _exchange.DisplayOrder = value;
                    RaisePropertyChanged(nameof(DisplayOrder));
                    ValidateProperty(_exchange, nameof(DisplayOrder));
                }
            }
        }

        public bool IsActive
        {
            get { return _exchange.IsActive; }
            set
            {
                if (_exchange.IsActive != value)
                {
                    _exchange.IsActive = value;
                    RaisePropertyChanged(nameof(IsActive));
                    ValidateProperty(_exchange, nameof(IsActive));
                }
            }
        }

        public bool ValidateModel()
        {
            return ValidateModel(_exchange);
        }
    }
}
