using System.Windows;
using TD.AppInfra.Commands;
using TD.i18n;
using TD.WPF.Services;
using TD.WPF.ViewModels.Trades;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.Commands.Trades
{
    public partial class TradeDetailCommand : AbstractCommand
    {
        protected readonly TradeListVM _viewModel;
        private readonly IWindowDialogService _windowDialogService;

        public TradeDetailCommand(TradeListVM viewModel, IWindowDialogService windowDialogService)
        {
            _viewModel = viewModel;
            _windowDialogService = windowDialogService;
        }

        public override bool CanExecute(object? parameter)
        {
            return _viewModel.SelectedTrade is not null;
        }

        public override async void Execute(object? parameter)
        {
            if (_viewModel.SelectedTrade is null)
                return;

            if (parameter is not Window owner)
                return;

            var trade = _viewModel.SelectedTrade;
            _windowDialogService.ShowTradeDetailDialog(owner, trade);
        }

    }
}