using System.Windows;
using TD.AppInfra.Commands;
using TD.AppInfra.Services;
using TD.i18n;
using TD.Models;
using TD.WPF.Services;
using TD.WPF.ViewModels.Trades;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.Commands.Trades
{
    public partial class TradeCreateCommand : AbstractCommand
    {
        protected readonly TradeListVM _viewModel;
        private readonly IWindowDialogService _windowDialogService;
        private readonly ISymbolLookupService _symbolLookupService;
        private readonly ITradingAccountLookupService _tradingAccountLookupService;

        public TradeCreateCommand(TradeListVM viewModel, IWindowDialogService windowDialogService,
                                  ISymbolLookupService symbolLookupService, ITradingAccountLookupService tradingAccountLookupService)
        {
            _viewModel = viewModel;
            _windowDialogService = windowDialogService;
            _symbolLookupService = symbolLookupService;
            _tradingAccountLookupService = tradingAccountLookupService;
        }

        public override async void Execute(object? parameter)
        {
            if (parameter is not Window owner)
                return;

            try
            {
                var dialogResult = _windowDialogService.ShowTradeCreateDialog(owner, _symbolLookupService, _tradingAccountLookupService, PreselectedTradingAccount);

                if (dialogResult.IsConfirmed && dialogResult.Trade is not null)
                {
                    var trade = dialogResult.Trade;
                    await _viewModel.SaveTradeAsync(trade);
                    await _viewModel.LoadTradesAsync();

                    _viewModel.SelectedTrade = _viewModel.Trades.FirstOrDefault(x => x.Id == trade.Id);
                }
            }
            catch (Exception ex)
            {
                string innerExceptionMsg = ex.InnerException != null ? $"\n{ex.InnerException.Message}" : "";
                MessageBox.Show($"{MessageStrings.SaveOperationFailed}\n{ex.Message}{innerExceptionMsg}",
                    CommonStrings.AppTitle,
                    MessageBoxButton.OK,
                    MessageBoxImage.Error);
            }
            finally
            {
                PreselectedTradingAccount = null;
            }
        }

        /// <summary>
        /// Before executing the command, we can set this property to have the tradingAccount preselected in the Trade creation dialog.
        /// This is useful when you want to create a Trade for a specific tradingAccount and want to save the user from having to select it manually.
        /// </summary>
        public TradingAccount? PreselectedTradingAccount { get; set; } = null;
    }
}