using TD.AppInfra.Commands;
using TD.WPF.ViewModels.Trades;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.Commands.Trades
{
    public partial class TradesLoadCommand : AbstractCommand
    {
        protected readonly TradeListVM _viewModel;

        public TradesLoadCommand(TradeListVM viewModel)
        {
            _viewModel = viewModel;
        }

        public override bool CanExecute(object? parameter)
        {
            return !_viewModel.LoadTradesInProgress;
        }

        public override async void Execute(object? parameter)
        {
            if (!CanExecute(parameter))
                return;

            _viewModel.QueryVM.Page = 1;
            await _viewModel.LoadTradesAsync();
            RaiseCanExecuteChanged();
        }
    }
}