//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using TD.Helpers;
using TD.Models;

namespace TD.RepositoryContracts
{
    public partial interface IExitOrderRepository
    {
        Task<IReadOnlyList<ExitOrder>> GetAllAsync();
        Task<bool> AnyByTradeIdAsync(int tradeId);
        Task<IReadOnlyList<ExitOrder>> GetByTradeIdAsync(int tradeId);
        Task<ExitOrder?> GetByIdAsync(int? id);
        Task<int> CreateAsync(ExitOrder exitOrder);
        Task<bool> CanDeleteAsync(int id);
        Task<bool> DeleteAsync(int id);
        Task<bool> UpdateAsync(ExitOrder exitOrder);
        Task<bool> UpdateCancellationTimeAsync(int id, DateTime cancellationTime);
    }
}