//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using TD.Helpers;
using TD.Models;

namespace TD.RepositoryContracts
{
    public partial interface ISessionRepository
    {
        Task<IReadOnlyList<Session>> GetAllAsync();
        Task<bool> AnyByExchangeIdAsync(int exchangeId);
        Task<IReadOnlyList<Session>> GetByExchangeIdAsync(int exchangeId);
        Task<Session?> GetByIdAsync(int? id);
        Task<int> CreateAsync(Session session);
        Task<bool> CanDeleteAsync(int id);
        Task<bool> DeleteAsync(int id);
        Task<bool> UpdateAsync(Session session);
    }
}