//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using TD.Helpers;
using TD.Models;

namespace TD.RepositoryContracts
{
    public partial interface ISymbolRepository
    {
        Task<IReadOnlyList<Symbol>> GetAllAsync(bool? isActive = null);
        Task<bool> AnyByExchangeIdAsync(int exchangeId);
        Task<IReadOnlyList<Symbol>> GetByExchangeIdAsync(int exchangeId, bool? isActive = null);
        Task<bool> AnyByPriceCurrencyIdAsync(int priceCurrencyId);
        Task<IReadOnlyList<Symbol>> GetByPriceCurrencyIdAsync(int priceCurrencyId, bool? isActive = null);
        Task<Symbol?> GetByIdAsync(int? id);
        Task<Symbol?> GetByTickerFullAsync(string? tickerFull);
        Task<IReadOnlyList<Symbol>> GetPagedAsync(QueryParameters queryParameters, bool? isActive = null);
        Task<int> CreateAsync(Symbol symbol);
        Task<bool> CanDeleteAsync(int id);
        Task<bool> DeleteAsync(int id);
        Task<bool> UpdateAsync(Symbol symbol);
    }
}