//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using TD.Helpers;
using TD.Models;

namespace TD.RepositoryContracts
{
    public partial interface ITradeNoteRepository
    {
        Task<IReadOnlyList<TradeNote>> GetAllAsync();
        Task<bool> AnyByTradeIdAsync(int tradeId);
        Task<IReadOnlyList<TradeNote>> GetByTradeIdAsync(int tradeId);
        Task<TradeNote?> GetByIdAsync(int? id);
        Task<int> CreateAsync(TradeNote tradeNote);
        Task<bool> CanDeleteAsync(int id);
        Task<bool> DeleteAsync(int id);
        Task<bool> UpdateAsync(TradeNote tradeNote);
    }
}