//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using TD.Helpers;
using TD.Models;

namespace TD.RepositoryContracts
{
    public partial interface ITradeRepository
    {
        Task<IReadOnlyList<Trade>> GetAllAsync();
        Task<bool> AnyBySymbolIdAsync(int symbolId);
        Task<IReadOnlyList<Trade>> GetBySymbolIdAsync(int symbolId);
        Task<bool> AnyByTradingAccountIdAsync(int tradingAccountId);
        Task<IReadOnlyList<Trade>> GetByTradingAccountIdAsync(int tradingAccountId);
        Task<Trade?> GetByIdAsync(int? id);
        Task<IReadOnlyList<Trade>> GetPagedAsync(TradeQueryParameters queryParameters);
        Task<int> CreateAsync(Trade trade);
        Task<bool> CanDeleteAsync(int id);
        Task<bool> DeleteAsync(int id);
        Task<bool> UpdateAsync(Trade trade);
        Task<bool> UpdateCancellationTimeAsync(int id, DateTime cancellationTime);
        Task<bool> UpdateReviewNotesAsync(int id, string reviewNotes);
        Task<bool> UpdateSetupNotesAsync(int id, string setupNotes);
    }
}