using System;
using System.Windows.Input;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.AppInfra.Commands
{
    public abstract class AbstractCommand : ICommand
    {
        public abstract void Execute(object? parameter);

        public virtual bool CanExecute(object? parameter)
        {
            return true;
        }

        public void RaiseCanExecuteChanged()
        {
            CanExecuteChanged?.Invoke(this, EventArgs.Empty);
        }

        public event EventHandler? CanExecuteChanged;
    }
}