using TD.Models;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.AppInfra.Services
{
    /// <summary>
    /// Defines a service for retrieving symbol information for use in lookup scenarios.
    /// </summary>
    /// <remarks>Implementations of this interface provide access to symbol data, typically for populating
    /// selection lists or validating symbol references in the application. Methods are asynchronous to support data
    /// sources that may require I/O operations, such as databases or remote services.</remarks>
    public partial interface ISymbolLookupService
    {
        Task<IReadOnlyList<Symbol>> GetSymbolsAsync(bool isActive);
    }
}
