using TD.Models;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.AppInfra.Services
{
    /// <summary>
    /// Defines a service for retrieving tradingAccount information for use in lookup scenarios.
    /// </summary>
    /// <remarks>Implementations of this interface provide access to tradingAccount data, typically for populating
    /// selection lists or validating tradingAccount references in the application. Methods are asynchronous to support data
    /// sources that may require I/O operations, such as databases or remote services.</remarks>
    public partial interface ITradingAccountLookupService
    {
        Task<IReadOnlyList<TradingAccount>> GetTradingAccountsAsync(bool isActive);
    }
}
