using System.ComponentModel.DataAnnotations;
using TD.Validation;
using TD.i18n;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.Models
{
    public partial class Exchange
    {
        public Exchange()
        {
            this.Symbols = new HashSet<Symbol>();
            this.Sessions = new HashSet<Session>();
            this.Holidays = new HashSet<Holiday>();
            this.TradingAccounts = new HashSet<TradingAccount>();
            this.DefaultCurrency = new Currency();
            this.ExchangeName = string.Empty;
            this.ExchangeCode = string.Empty;
            this.CountryCode = string.Empty;
            this.Timezone = string.Empty;

            OnInitilazed();
        }
        /// <summary>
        /// PrimaryKey field
        /// </summary>
        [Key]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Id")]
        public int Id { get; set; }

        [StringLength(48, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExchangeName")]
        public string ExchangeName { get; set; }

        [StringLength(8, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExchangeCode")]
        public string ExchangeCode { get; set; }

        [StringLength(4, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "CountryCode")]
        public string CountryCode { get; set; }

        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "DefaultCurrencyId")]
        public int DefaultCurrencyId { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "DefaultCurrency")]
        public Currency DefaultCurrency { get; set; }

        /// <summary>
        /// IANA timezone name
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Timezone")]
        public string Timezone { get; set; }

        /// <summary>
        /// It's true for 24/7 open markets others respect to their related records at Sessions and Holidays
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "IsAlwaysOpen")]
        public bool IsAlwaysOpen { get; set; }

        /// <summary>
        /// Determine if the exchange has any symbol.
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "HasAnySymbol")]
        public bool HasAnySymbol { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "Symbols")]
        public ICollection<Symbol> Symbols { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "Sessions")]
        public ICollection<Session> Sessions { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "Holidays")]
        public ICollection<Holiday> Holidays { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradingAccounts")]
        public ICollection<TradingAccount> TradingAccounts { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "DisplayOrder")]
        public int DisplayOrder { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "IsActive")]
        public bool IsActive { get; set; }


        /// <summary>
        /// Clones all properties in a new Exchange instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New Exchange instance</returns>
        public Exchange Clone()
        {
            var clone = new Exchange();
            clone.ExchangeName = this.ExchangeName;
            clone.ExchangeCode = this.ExchangeCode;
            clone.CountryCode = this.CountryCode;
            clone.DefaultCurrencyId = this.DefaultCurrencyId;
            clone.Timezone = this.Timezone;
            clone.IsAlwaysOpen = this.IsAlwaysOpen;
            clone.HasAnySymbol = this.HasAnySymbol;
            clone.DisplayOrder = this.DisplayOrder;
            clone.IsActive = this.IsActive;

            Cloning(clone);
            return clone;
        }

        // Use below method in a partial class file (eg. Exchange.part.cs)
        // to add more detailed data to clone
        partial void Cloning(Exchange clone);


        // Use below method in a partial class file (eg. Exchange.part.cs)
        // to add some functionality after the constructor
        partial void OnInitilazed();
    }
}
