using System.ComponentModel.DataAnnotations;
using TD.Validation;
using TD.i18n;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.Models
{
    public partial class Holiday
    {
        public Holiday()
        {
            this.Exchange = new Exchange();
            this.HolidayName = string.Empty;

            OnInitilazed();
        }
        /// <summary>
        /// PrimaryKey field
        /// </summary>
        [Key]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Id")]
        public int Id { get; set; }

        [StringLength(200, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "HolidayName")]
        public string HolidayName { get; set; }

        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExchangeId")]
        public int ExchangeId { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "Exchange")]
        public Exchange Exchange { get; set; }

        /// <summary>
        /// For fixed-date holidays (e.g., July 4th, April 23rd)
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Month")]
        public int? Month { get; set; }

        /// <summary>
        /// For fixed-date holidays (e.g., July 4th, April 23rd)
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Day")]
        public int? Day { get; set; }

        /// <summary>
        /// For floating holidays (e.g., Ramadan Feast, Chinese New Year)
        /// </summary>
        [DataType(DataType.Date)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "HolidayDate")]
        public DateTime? HolidayDate { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "IsHalfDay")]
        public bool IsHalfDay { get; set; }


        /// <summary>
        /// Clones all properties in a new Holiday instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New Holiday instance</returns>
        public Holiday Clone()
        {
            var clone = new Holiday();
            clone.HolidayName = this.HolidayName;
            clone.ExchangeId = this.ExchangeId;
            clone.Month = this.Month;
            clone.Day = this.Day;
            clone.HolidayDate = this.HolidayDate;
            clone.IsHalfDay = this.IsHalfDay;

            Cloning(clone);
            return clone;
        }

        // Use below method in a partial class file (eg. Holiday.part.cs)
        // to add more detailed data to clone
        partial void Cloning(Holiday clone);


        // Use below method in a partial class file (eg. Holiday.part.cs)
        // to add some functionality after the constructor
        partial void OnInitilazed();
    }
}
