using System.ComponentModel.DataAnnotations;
using TD.Validation;
using TD.i18n;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.Models
{
    public partial class Session
    {
        public Session()
        {
            this.Exchange = new Exchange();
            this.LocalOpen = string.Empty;
            this.LocalClose = string.Empty;

            OnInitilazed();
        }
        /// <summary>
        /// PrimaryKey field
        /// </summary>
        [Key]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Id")]
        public int Id { get; set; }

        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExchangeId")]
        public int ExchangeId { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "Exchange")]
        public Exchange Exchange { get; set; }

        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "SessionType")]
        public SessionType SessionType { get; set; }

        /// <summary>
        /// 0=Sunday ... 6=Saturday, NULL=all days
        /// </summary>
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "DayOfWeek")]
        public int? DayOfWeek { get; set; }

        /// <summary>
        /// Opening hour in "HH:mm" format
        /// </summary>
        [StringLength(10, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "LocalOpen")]
        public string LocalOpen { get; set; }

        /// <summary>
        /// Closing hour in "HH:mm" format
        /// </summary>
        [StringLength(10, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "LocalClose")]
        public string LocalClose { get; set; }


        /// <summary>
        /// Clones all properties in a new Session instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New Session instance</returns>
        public Session Clone()
        {
            var clone = new Session();
            clone.ExchangeId = this.ExchangeId;
            clone.SessionType = this.SessionType;
            clone.DayOfWeek = this.DayOfWeek;
            clone.LocalOpen = this.LocalOpen;
            clone.LocalClose = this.LocalClose;

            Cloning(clone);
            return clone;
        }

        // Use below method in a partial class file (eg. Session.part.cs)
        // to add more detailed data to clone
        partial void Cloning(Session clone);


        // Use below method in a partial class file (eg. Session.part.cs)
        // to add some functionality after the constructor
        partial void OnInitilazed();
    }
}
