using System.ComponentModel.DataAnnotations;
using TD.Validation;
using TD.i18n;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.Models
{
    public partial class TakeProfitOrder
    {
        public TakeProfitOrder()
        {
            this.Trade = new Trade();

            OnInitilazed();
        }
        /// <summary>
        /// PrimaryKey field
        /// </summary>
        [Key]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Id")]
        public int Id { get; set; }

        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Range(1, int.MaxValue, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName ="ValueMin")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradeId")]
        public int TradeId { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "Trade")]
        public Trade Trade { get; set; }

        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "OrderType")]
        public ExitOrderType OrderType { get; set; }

        [GreaterThan(0)]
        [PriceSide(PriceSide.Above)]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "OrderPrice")]
        public decimal OrderPrice { get; set; }

        /// <summary>
        /// Executed Entry Price
        /// </summary>
        [GreaterThan(0)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "FilledPrice")]
        public decimal? FilledPrice { get; set; }

        /// <summary>
        /// Planned contract quantity of order
        /// </summary>
        [GreaterThan(0)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "OrderQuantity")]
        public decimal? OrderQuantity { get; set; }

        /// <summary>
        /// Realized contract quantity of order
        /// </summary>
        [GreaterThan(0)]
        [NotGreaterThanProperty(nameof(OrderQuantity))]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "FilledQuantity")]
        public decimal? FilledQuantity { get; set; }

        [StringLength(512, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [DataType(DataType.MultilineText)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Notes")]
        public string? Notes { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "CancellationTime")]
        public DateTime? CancellationTime { get; set; }

        [Range(typeof(DateTime), "2000-01-01", "2220-12-31", ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName ="RangeDateTime")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "FilledTime")]
        public DateTime? FilledTime { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [DataType(DataType.Date)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "UpdatedAt")]
        public DateTime UpdatedAt { get; set; }


        /// <summary>
        /// Clones all properties in a new TakeProfitOrder instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New TakeProfitOrder instance</returns>
        public TakeProfitOrder Clone()
        {
            var clone = new TakeProfitOrder();
            clone.TradeId = this.TradeId;
            clone.OrderType = this.OrderType;
            clone.OrderPrice = this.OrderPrice;
            clone.FilledPrice = this.FilledPrice;
            clone.OrderQuantity = this.OrderQuantity;
            clone.FilledQuantity = this.FilledQuantity;
            clone.Notes = this.Notes;
            clone.CancellationTime = this.CancellationTime;
            clone.FilledTime = this.FilledTime;
            clone.UpdatedAt = this.UpdatedAt;

            Cloning(clone);
            return clone;
        }

        // Use below method in a partial class file (eg. TakeProfitOrder.part.cs)
        // to add more detailed data to clone
        partial void Cloning(TakeProfitOrder clone);


        // Use below method in a partial class file (eg. TakeProfitOrder.part.cs)
        // to add some functionality after the constructor
        partial void OnInitilazed();
    }
}
