using System.ComponentModel.DataAnnotations;
using TD.i18n;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.Models
{
    public partial class TradeNote
    {
        public TradeNote()
        {
            this.TradeImages = new HashSet<TradeImage>();
            this.Trade = new Trade();
            this.Content = string.Empty;

            OnInitilazed();
        }
        /// <summary>
        /// PrimaryKey field
        /// </summary>
        [Key]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Id")]
        public int Id { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradeId")]
        public int TradeId { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "Trade")]
        public Trade Trade { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Category")]
        public TradeNoteCategory Category { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "Adherence")]
        public TradeAdherence? Adherence { get; set; }

        [StringLength(2048, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Content")]
        public string Content { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradeImages")]
        public ICollection<TradeImage> TradeImages { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [DataType(DataType.Date)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "UpdatedAt")]
        public DateTime UpdatedAt { get; set; }


        /// <summary>
        /// Clones all properties in a new TradeNote instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New TradeNote instance</returns>
        public TradeNote Clone()
        {
            var clone = new TradeNote();
            clone.TradeId = this.TradeId;
            clone.Category = this.Category;
            clone.Adherence = this.Adherence;
            clone.Content = this.Content;
            clone.UpdatedAt = this.UpdatedAt;

            Cloning(clone);
            return clone;
        }

        // Use below method in a partial class file (eg. TradeNote.part.cs)
        // to add more detailed data to clone
        partial void Cloning(TradeNote clone);


        // Use below method in a partial class file (eg. TradeNote.part.cs)
        // to add some functionality after the constructor
        partial void OnInitilazed();
    }
}
