using System.ComponentModel.DataAnnotations;
using TD.Validation;
using TD.i18n;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.Models
{
    public partial class TradingAccount
    {
        public TradingAccount()
        {
            this.Exchange = new Exchange();
            this.Title = string.Empty;

            OnInitilazed();
        }
        /// <summary>
        /// PrimaryKey field
        /// </summary>
        [Key]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Id")]
        public int Id { get; set; }

        [StringLength(128, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// The Id value of exchange record that related to the account.
        /// </summary>
        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExchangeId")]
        public int ExchangeId { get; set; }

        /// <summary>
        /// Exchange of the account.
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Exchange")]
        public Exchange Exchange { get; set; }

        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "MarketType")]
        public MarketType MarketType { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "MakerFeeRate")]
        public decimal? MakerFeeRate { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "TakerFeeRate")]
        public decimal? TakerFeeRate { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Notes")]
        public string? Notes { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "DisplayOrder")]
        public int DisplayOrder { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "IsActive")]
        public bool IsActive { get; set; }


        /// <summary>
        /// Clones all properties in a new TradingAccount instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New TradingAccount instance</returns>
        public TradingAccount Clone()
        {
            var clone = new TradingAccount();
            clone.Title = this.Title;
            clone.ExchangeId = this.ExchangeId;
            clone.MarketType = this.MarketType;
            clone.MakerFeeRate = this.MakerFeeRate;
            clone.TakerFeeRate = this.TakerFeeRate;
            clone.Notes = this.Notes;
            clone.DisplayOrder = this.DisplayOrder;
            clone.IsActive = this.IsActive;

            Cloning(clone);
            return clone;
        }

        // Use below method in a partial class file (eg. TradingAccount.part.cs)
        // to add more detailed data to clone
        partial void Cloning(TradingAccount clone);


        // Use below method in a partial class file (eg. TradingAccount.part.cs)
        // to add some functionality after the constructor
        partial void OnInitilazed();
    }
}
