using System.ComponentModel.DataAnnotations;
using TD.Validation;
using TD.i18n;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.Models
{
    public partial class Trade
    {
        public Trade()
        {
            this.EntryOrders = new HashSet<EntryOrder>();
            this.TakeProfitOrders = new HashSet<TakeProfitOrder>();
            this.StopLossOrders = new HashSet<StopLossOrder>();
            this.TradeImages = new HashSet<TradeImage>();
            this.TradingAccount = new TradingAccount();
            this.Symbol = new Symbol();

            OnInitilazed();
        }
        /// <summary>
        /// PrimaryKey field
        /// </summary>
        [Key]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Id")]
        public int Id { get; set; }

        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradingAccountId")]
        public int TradingAccountId { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradingAccount")]
        public TradingAccount TradingAccount { get; set; }

        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "SymbolId")]
        public int SymbolId { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "Symbol")]
        public Symbol Symbol { get; set; }

        [DataType(DataType.DateTime)]
        [Range(typeof(DateTime), "2000-01-01", "2220-12-31", ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName ="RangeDateTime")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "EntryTime")]
        public DateTime? EntryTime { get; set; }

        [DataType(DataType.DateTime)]
        [Range(typeof(DateTime), "2000-01-01", "2220-12-31", ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName ="RangeDateTime")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExitTime")]
        public DateTime? ExitTime { get; set; }

        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradeDirection")]
        public TradeDirection TradeDirection { get; set; }

        /// <summary>
        /// Missed (-10), Cancelled (-20), Planned (10), Pending (20), Active (30), Closed (40). Negative values mean never opened. TradeStatus > TradeStatus.Pending means trade active or closed and may have a result
        /// </summary>
        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradeStatus")]
        public TradeStatus TradeStatus { get; set; }

        [RequiredSelection]
        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "MarketType")]
        public MarketType MarketType { get; set; }

        /// <summary>
        /// Time stamp, when TradeStatus is set to TradeStatus.Cancelled
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "CancellationTime")]
        public DateTime? CancellationTime { get; set; }

        /// <summary>
        /// Planned Entry Price, calculated from EntryOrders, also persisted for using in SQL queries.
        /// </summary>
        [GreaterThan(0)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "PlannedEntryPrice")]
        public decimal? PlannedEntryPrice { get; set; }

        /// <summary>
        /// Executed Entry Price, calculated from EntryOrders, also persisted for using in SQL queries.
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExecutedEntryPrice")]
        public decimal? ExecutedEntryPrice { get; set; }

        /// <summary>
        /// Planned contract quantity of entry orders, calculated from EntryOrders. Also persisted for using in SQL queries.
        /// </summary>
        [GreaterThan(0)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "OrderQuantity")]
        public decimal? OrderQuantity { get; set; }

        /// <summary>
        /// Realized contract quantity of entry orders, calculated from EntryOrders. Also persisted for using in SQL queries.
        /// </summary>
        [GreaterThan(0)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "FilledQuantity")]
        public decimal? FilledQuantity { get; set; }

        /// <summary>
        /// Planned Take Profit Price, calculated from TakeProfitOrders
        /// </summary>
        [GreaterThan(0)]
        [PriceSide(PriceSide.Above)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "PlannedTP")]
        public decimal? PlannedTP { get; set; }

        /// <summary>
        /// Executed Take Profit Price, calculated from TakeProfitOrders
        /// </summary>
        [GreaterThan(0)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExecutedTP")]
        public decimal? ExecutedTP { get; set; }

        /// <summary>
        /// Planned Stop Loss Price, calculated from StopLossOrders
        /// </summary>
        [GreaterThan(0)]
        [PriceSide(PriceSide.Below)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "PlannedSL")]
        public decimal? PlannedSL { get; set; }

        /// <summary>
        /// Executed Stop Loss Price, calculated from StopLossOrders
        /// </summary>
        [GreaterThan(0)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ExecutedSL")]
        public decimal? ExecutedSL { get; set; }

        /// <summary>
        /// User override; used if set
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "TotalFeesCorrected")]
        public decimal? TotalFeesCorrected { get; set; }

        [GreaterThan(0)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "FundingFeeTotal")]
        public decimal? FundingFeeTotal { get; set; }

        [StringLength(255, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [DataType(DataType.MultilineText)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "Tags")]
        public string? Tags { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "EntryOrders")]
        public ICollection<EntryOrder> EntryOrders { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "TakeProfitOrders")]
        public ICollection<TakeProfitOrder> TakeProfitOrders { get; set; }

        [Display(ResourceType = typeof(LocalizedStrings), Name = "StopLossOrders")]
        public ICollection<StopLossOrder> StopLossOrders { get; set; }

        [StringLength(2048, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [DataType(DataType.MultilineText)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "SetupNotes")]
        public string? SetupNotes { get; set; }

        [StringLength(2048, ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "MaxStringLength")]
        [DataType(DataType.MultilineText)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "ReviewNotes")]
        public string? ReviewNotes { get; set; }

        /// <summary>
        /// Keeps Web URL or local file path of the images associated with the trade, along with optional notes. This collection allows for multiple images to be linked to a single trade, providing visual documentation or evidence of the trade setup, execution, or outcome. Each TradeImage instance contains details about the image and its relation to the trade, facilitating better organization and reference within the trading diary.
        /// </summary>
        [Display(ResourceType = typeof(LocalizedStrings), Name = "TradeImages")]
        public ICollection<TradeImage> TradeImages { get; set; }

        [Required(ErrorMessageResourceType = typeof(ErrorStrings), ErrorMessageResourceName = "Required")]
        [DataType(DataType.Date)]
        [Display(ResourceType = typeof(LocalizedStrings), Name = "UpdatedAt")]
        public DateTime UpdatedAt { get; set; }


        /// <summary>
        /// Clones all properties in a new Trade instance,
        /// except PrimaryKey(s)
        /// </summary>
        /// <returns>New Trade instance</returns>
        public Trade Clone()
        {
            var clone = new Trade();
            clone.TradingAccountId = this.TradingAccountId;
            clone.SymbolId = this.SymbolId;
            clone.EntryTime = this.EntryTime;
            clone.ExitTime = this.ExitTime;
            clone.TradeDirection = this.TradeDirection;
            clone.TradeStatus = this.TradeStatus;
            clone.MarketType = this.MarketType;
            clone.CancellationTime = this.CancellationTime;
            clone.PlannedEntryPrice = this.PlannedEntryPrice;
            clone.ExecutedEntryPrice = this.ExecutedEntryPrice;
            clone.OrderQuantity = this.OrderQuantity;
            clone.FilledQuantity = this.FilledQuantity;
            clone.PlannedTP = this.PlannedTP;
            clone.ExecutedTP = this.ExecutedTP;
            clone.PlannedSL = this.PlannedSL;
            clone.ExecutedSL = this.ExecutedSL;
            clone.TotalFeesCorrected = this.TotalFeesCorrected;
            clone.FundingFeeTotal = this.FundingFeeTotal;
            clone.Tags = this.Tags;
            clone.SetupNotes = this.SetupNotes;
            clone.ReviewNotes = this.ReviewNotes;
            clone.UpdatedAt = this.UpdatedAt;

            Cloning(clone);
            return clone;
        }

        // Use below method in a partial class file (eg. Trade.part.cs)
        // to add more detailed data to clone
        partial void Cloning(Trade clone);


        // Use below method in a partial class file (eg. Trade.part.cs)
        // to add some functionality after the constructor
        partial void OnInitilazed();
    }
}
