using TD.AppInfra.ViewModels;
using TD.Models;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Maintenance
{
    public partial class CurrencyEditVM : AbstractCreateEditVM
    {
        private Currency _currency;
        public Currency Currency => _currency;

        public CurrencyEditVM(Currency currency)
        {
            _currency = currency;
            OnInitialized();
        }
        partial void OnInitialized();

        public string CurrencyTicker => _currency.CurrencyTicker;

        public string? Description
        {
            get { return _currency.Description; }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && _currency.Description != value)
                {
                    _currency.Description = value;
                    RaisePropertyChanged(nameof(Description));
                    ValidateProperty(_currency, nameof(Description));
                }
                else if (string.IsNullOrWhiteSpace(value))
                {
                    _currency.Description = null;
                    RaisePropertyChanged(nameof(Description));
                    ValidateProperty(_currency, nameof(Description));
                }
            }
        }

        public int DisplayOrder
        {
            get { return _currency.DisplayOrder; }
            set
            {
                if (_currency.DisplayOrder != value)
                {
                    _currency.DisplayOrder = value;
                    RaisePropertyChanged(nameof(DisplayOrder));
                    ValidateProperty(_currency, nameof(DisplayOrder));
                }
            }
        }

        public bool IsActive
        {
            get { return _currency.IsActive; }
            set
            {
                if (_currency.IsActive != value)
                {
                    _currency.IsActive = value;
                    RaisePropertyChanged(nameof(IsActive));
                    ValidateProperty(_currency, nameof(IsActive));
                }
            }
        }

        public bool ValidateModel()
        {
            return ValidateModel(_currency);
        }
    }
}
