using System.Collections.ObjectModel;
using TD.AppInfra.Services;
using TD.AppInfra.ViewModels;
using TD.Extensions;
using TD.Models;
using static TD.Extensions.EnumExtension;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------

namespace TD.WPF.ViewModels.Maintenance
{
    public partial class SymbolCreateVM : AbstractCreateEditVM
    {
        private readonly ICurrencyLookupService _currencyLookupService;
        private readonly IExchangeLookupService _exchangeLookupService;
        private Symbol _symbol;
        public Symbol Symbol => _symbol;

        public SymbolCreateVM(ICurrencyLookupService currencyLookupService, IExchangeLookupService exchangeLookupService)
        {
            _currencyLookupService = currencyLookupService;
            Currencies = new ObservableCollection<Currency>();

            _exchangeLookupService = exchangeLookupService;
            Exchanges = new ObservableCollection<Exchange>();

            _symbol = new Symbol();
            DisplayOrder = 1000;
            IsActive = true;
            MarketTypeValues = GetValues<MarketType>();
            OnInitialized();
        }
        partial void OnInitialized();

        public ObservableCollection<Currency> Currencies { get; }

        public async Task LoadCurrenciesAsync()
        {
            var items = await _currencyLookupService.GetCurrenciesAsync(isActive: true);
            Currencies.Clear();
            foreach (var item in items)
            {
                Currencies.Add(item);
            }
        }

        public ObservableCollection<Exchange> Exchanges { get; }

        public async Task LoadExchangesAsync()
        {
            var items = await _exchangeLookupService.GetExchangesAsync(isActive: true);
            Exchanges.Clear();
            foreach (var item in items)
            {
                Exchanges.Add(item);
            }
        }

        /// <summary>
        /// Gets the collection of available MarketType enum members for selection or display.
        /// </summary>
        public IEnumerable<EnumValueItem<MarketType>> MarketTypeValues { get; }

        public string Ticker
        {
            get { return _symbol.Ticker; }
            set
            {
                if (_symbol.Ticker != value)
                {
                    _symbol.Ticker = value.ToUpperInvariant();
                    RaisePropertyChanged(nameof(Ticker));
                    ValidateProperty(_symbol, nameof(Ticker));
                }
            }
        }

        public string TickerFull
        {
            get { return _symbol.TickerFull; }
            set
            {
                if (_symbol.TickerFull != value)
                {
                    _symbol.TickerFull = value.ToUpperInvariant();
                    RaisePropertyChanged(nameof(TickerFull));
                    ValidateProperty(_symbol, nameof(TickerFull));
                }
            }
        }

        public string? BaseCurrency
        {
            get { return _symbol.BaseCurrency; }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && _symbol.BaseCurrency != value)
                {
                    _symbol.BaseCurrency = value.ToUpperInvariant();
                    RaisePropertyChanged(nameof(BaseCurrency));
                    ValidateProperty(_symbol, nameof(BaseCurrency));
                }
                else if (string.IsNullOrWhiteSpace(value))
                {
                    _symbol.BaseCurrency = null;
                    RaisePropertyChanged(nameof(BaseCurrency));
                    ValidateProperty(_symbol, nameof(BaseCurrency));
                }
            }
        }

        public int PriceCurrencyId
        {
            get { return _symbol.PriceCurrencyId; }
            set
            {
                if (_symbol.PriceCurrencyId != value)
                {
                    _symbol.PriceCurrencyId = value;
                    RaisePropertyChanged(nameof(PriceCurrencyId));
                    ValidateProperty(_symbol, nameof(PriceCurrencyId));
                }
            }
        }

        public Currency PriceCurrency
        {
            get { return _symbol.PriceCurrency; }
            set
            {
                if (_symbol.PriceCurrency != value)
                {
                    _symbol.PriceCurrency = value;
                    RaisePropertyChanged(nameof(PriceCurrency));
                    ValidateProperty(_symbol, nameof(PriceCurrency));
                }
            }
        }

        public string? Description
        {
            get { return _symbol.Description; }
            set
            {
                if (!string.IsNullOrWhiteSpace(value) && _symbol.Description != value)
                {
                    _symbol.Description = value;
                    RaisePropertyChanged(nameof(Description));
                    ValidateProperty(_symbol, nameof(Description));
                }
                else if (string.IsNullOrWhiteSpace(value))
                {
                    _symbol.Description = null;
                    RaisePropertyChanged(nameof(Description));
                    ValidateProperty(_symbol, nameof(Description));
                }
            }
        }

        public int ExchangeId
        {
            get { return _symbol.ExchangeId; }
            set
            {
                if (_symbol.ExchangeId != value)
                {
                    _symbol.ExchangeId = value;
                    RaisePropertyChanged(nameof(ExchangeId));
                    ValidateProperty(_symbol, nameof(ExchangeId));
                }
            }
        }

        public Exchange Exchange
        {
            get { return _symbol.Exchange; }
            set
            {
                if (_symbol.Exchange != value)
                {
                    _symbol.Exchange = value;
                    RaisePropertyChanged(nameof(Exchange));
                    ValidateProperty(_symbol, nameof(Exchange));
                }
            }
        }

        public MarketType MarketType
        {
            get { return _symbol.MarketType; }
            set
            {
                if (_symbol.MarketType != value)
                {
                    _symbol.MarketType = value;
                    RaisePropertyChanged(nameof(MarketType));
                    ValidateProperty(_symbol, nameof(MarketType));
                }
            }
        }

        public int DisplayOrder
        {
            get { return _symbol.DisplayOrder; }
            set
            {
                if (_symbol.DisplayOrder != value)
                {
                    _symbol.DisplayOrder = value;
                    RaisePropertyChanged(nameof(DisplayOrder));
                    ValidateProperty(_symbol, nameof(DisplayOrder));
                }
            }
        }

        public bool IsActive
        {
            get { return _symbol.IsActive; }
            set
            {
                if (_symbol.IsActive != value)
                {
                    _symbol.IsActive = value;
                    RaisePropertyChanged(nameof(IsActive));
                    ValidateProperty(_symbol, nameof(IsActive));
                }
            }
        }

        public bool ValidateModel()
        {
            return ValidateModel(_symbol);
        }
    }
}
