using System.Windows;
using TD.AppInfra.Services;
using TD.AppInfra.ViewModels;
using TD.Models;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.WPF.Services
{
    public partial interface IWindowDialogService
    {
        /// <summary>
        /// Displays the Currency creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Currency, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Currency if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, Currency? Currency) ShowCurrencyCreateDialog(Window owner);

        /// <summary>
        /// Displays a modal dialog for editing the specified Currency and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="currency">The Currency entity to edit. The dialog will display and allow editing of this currency's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the currency
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowCurrencyEditDialog(Window owner, Currency currency);

        /// <summary>
        /// Displays the Entry Order creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Entry Order, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <param name="preselectedTrade">An optional preselected trade to initialize the dialog with.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Entry Order if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, EntryOrder? EntryOrder) ShowEntryOrderCreateDialog(Window owner, Trade? preselectedTrade);

        /// <summary>
        /// Displays a modal dialog for editing the specified Entry Order and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="entryOrder">The Entry Order entity to edit. The dialog will display and allow editing of this entryOrder's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the entryOrder
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowEntryOrderEditDialog(Window owner, EntryOrder entryOrder);

        /// <summary>
        /// Displays the Exchange creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Exchange, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <param name="currencyLookupService">The currency lookup service used to provide currency selection options within the dialog.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Exchange if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, Exchange? Exchange) ShowExchangeCreateDialog(Window owner, ICurrencyLookupService currencyLookupService);

        /// <summary>
        /// Displays a modal dialog for editing the specified Exchange and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="exchange">The Exchange entity to edit. The dialog will display and allow editing of this exchange's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the exchange
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowExchangeEditDialog(Window owner, Exchange exchange);

        /// <summary>
        /// Displays the Stop Loss Order creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Stop Loss Order, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <param name="preselectedTrade">An optional preselected trade to initialize the dialog with.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Stop Loss Order if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, StopLossOrder? StopLossOrder) ShowStopLossOrderCreateDialog(Window owner, Trade? preselectedTrade);

        /// <summary>
        /// Displays a modal dialog for editing the specified Stop Loss Order and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="stopLossOrder">The Stop Loss Order entity to edit. The dialog will display and allow editing of this stopLossOrder's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the stopLossOrder
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowStopLossOrderEditDialog(Window owner, StopLossOrder stopLossOrder);

        /// <summary>
        /// Displays the Symbol creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Symbol, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <param name="currencyLookupService">The currency lookup service used to provide currency selection options within the dialog.</param>
        /// <param name="exchangeLookupService">The exchange lookup service used to provide exchange selection options within the dialog.</param>
        /// <param name="preselectedExchange">An optional preselected exchange to initialize the dialog with.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Symbol if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, Symbol? Symbol) ShowSymbolCreateDialog(Window owner, ICurrencyLookupService currencyLookupService,
                                                                  IExchangeLookupService exchangeLookupService, Exchange? preselectedExchange);

        /// <summary>
        /// Displays a modal dialog for editing the specified Symbol and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="symbol">The Symbol entity to edit. The dialog will display and allow editing of this symbol's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the symbol
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowSymbolEditDialog(Window owner, Symbol symbol);

        /// <summary>
        /// Displays the Take Profit Order creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Take Profit Order, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <param name="preselectedTrade">An optional preselected trade to initialize the dialog with.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Take Profit Order if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, TakeProfitOrder? TakeProfitOrder) ShowTakeProfitOrderCreateDialog(Window owner, Trade? preselectedTrade);

        /// <summary>
        /// Displays a modal dialog for editing the specified Take Profit Order and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="takeProfitOrder">The Take Profit Order entity to edit. The dialog will display and allow editing of this takeProfitOrder's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the takeProfitOrder
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowTakeProfitOrderEditDialog(Window owner, TakeProfitOrder takeProfitOrder);

        /// <summary>
        /// Displays the Trade creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Trade, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <param name="symbolLookupService">The symbol lookup service used to provide symbol selection options within the dialog.</param>
        /// <param name="tradingAccountLookupService">The tradingAccount lookup service used to provide tradingAccount selection options within the dialog.</param>
        /// <param name="preselectedTradingAccount">An optional preselected tradingAccount to initialize the dialog with.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Trade if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, Trade? Trade) ShowTradeCreateDialog(Window owner, ISymbolLookupService symbolLookupService,
                                                               ITradingAccountLookupService tradingAccountLookupService, TradingAccount? preselectedTradingAccount);

        /// <summary>
        /// Displays a modal dialog for editing the specified Trade and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="trade">The Trade entity to edit. The dialog will display and allow editing of this trade's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the trade
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowTradeEditDialog(Window owner, Trade trade);

        /// <summary>
        /// Displays a dialog showing detailed information for the specified trade.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="trade">The trade entity to display in the detail dialog.</param>
        void ShowTradeDetailDialog(Window owner, Trade trade);

        /// <summary>
        /// Displays the Trade Image creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Trade Image, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <param name="preselectedTrade">An optional preselected trade to initialize the dialog with.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Trade Image if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, TradeImage? TradeImage) ShowTradeImageCreateDialog(Window owner, Trade? preselectedTrade);

        /// <summary>
        /// Displays a modal dialog for editing the specified Trade Image and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="tradeImage">The Trade Image entity to edit. The dialog will display and allow editing of this tradeImage's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the tradeImage
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowTradeImageEditDialog(Window owner, TradeImage tradeImage);

        /// <summary>
        /// Displays a dialog showing detailed information for the specified tradeImage.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="tradeImage">The tradeImage entity to display in the detail dialog.</param>
        void ShowTradeImageDetailDialog(Window owner, TradeImage tradeImage);

        /// <summary>
        /// Displays the Trading Account creation dialog and returns the result indicating whether the user confirmed the dialog
        /// and the created Trading Account, if any.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This determines the dialog's parent window for modality and positioning.</param>
        /// <param name="exchangeLookupService">The exchange lookup service used to provide exchange selection options within the dialog.</param>
        /// <param name="preselectedExchange">An optional preselected exchange to initialize the dialog with.</param>
        /// <returns>A tuple containing a Boolean value that is <see langword="true"/> if the user confirmed the dialog; otherwise, <see
        /// langword="false"/>. The second item is the created Trading Account if confirmed; otherwise, <see langword="null"/>.</returns>
        (bool IsConfirmed, TradingAccount? TradingAccount) ShowTradingAccountCreateDialog(Window owner, IExchangeLookupService exchangeLookupService,
                                                                                          Exchange? preselectedExchange);

        /// <summary>
        /// Displays a modal dialog for editing the specified Trading Account and returns the result indicating whether the dialog
        /// was confirmed and if any changes were made.
        /// </summary>
        /// <param name="owner">The window that will own the dialog. This parameter determines the parent window for modal behavior and dialog
        /// positioning.</param>
        /// <param name="tradingAccount">The Trading Account entity to edit. The dialog will display and allow editing of this tradingAccount's properties.</param>
        /// <returns>A tuple containing two values: IsConfirmed is <see langword="true"/> if the user confirmed the dialog;
        /// otherwise, <see langword="false"/>. IsDirty is <see langword="true"/> if any changes were made to the tradingAccount
        /// during editing; otherwise, <see langword="false"/>.</returns>
        (bool IsConfirmed, bool IsDirty) ShowTradingAccountEditDialog(Window owner, TradingAccount tradingAccount);

    }
}