using System.Windows;
using TD.AppInfra.Services;
using TD.AppInfra.ViewModels;
using TD.Models;
using TD.WPF.Views.Exchanges;
using TD.WPF.Views.Maintenance;
using TD.WPF.Views.Trades;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.WPF.Services
{
    public partial class WindowDialogService : IWindowDialogService
    {
        /// <inheritdoc />
        public (bool IsConfirmed, Currency? Currency) ShowCurrencyCreateDialog(Window owner)
        {
            var dialog = new CurrencyCreateView()
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, result ? dialog.Currency : null);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, bool IsDirty) ShowCurrencyEditDialog(Window owner, Currency currency)
        {
            var dialog = new CurrencyEditView(currency)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, dialog.IsDirty);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, EntryOrder? EntryOrder) ShowEntryOrderCreateDialog(Window owner, Trade? preselectedTrade)
        {
            var dialog = new EntryOrderCreateView(preselectedTrade)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, result ? dialog.EntryOrder : null);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, bool IsDirty) ShowEntryOrderEditDialog(Window owner, EntryOrder entryOrder)
        {
            var dialog = new EntryOrderEditView(entryOrder)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, dialog.IsDirty);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, Exchange? Exchange) ShowExchangeCreateDialog(Window owner, ICurrencyLookupService currencyLookupService)
        {
            var dialog = new ExchangeCreateView(currencyLookupService)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, result ? dialog.Exchange : null);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, bool IsDirty) ShowExchangeEditDialog(Window owner, Exchange exchange)
        {
            var dialog = new ExchangeEditView(exchange)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, dialog.IsDirty);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, StopLossOrder? StopLossOrder) ShowStopLossOrderCreateDialog(Window owner, Trade? preselectedTrade)
        {
            var dialog = new StopLossOrderCreateView(preselectedTrade)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, result ? dialog.StopLossOrder : null);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, bool IsDirty) ShowStopLossOrderEditDialog(Window owner, StopLossOrder stopLossOrder)
        {
            var dialog = new StopLossOrderEditView(stopLossOrder)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, dialog.IsDirty);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, Symbol? Symbol) ShowSymbolCreateDialog(Window owner, ICurrencyLookupService currencyLookupService,
                                                                         IExchangeLookupService exchangeLookupService, Exchange? preselectedExchange)
        {
            var dialog = new SymbolCreateView(currencyLookupService, exchangeLookupService, preselectedExchange)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, result ? dialog.Symbol : null);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, bool IsDirty) ShowSymbolEditDialog(Window owner, Symbol symbol)
        {
            var dialog = new SymbolEditView(symbol)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, dialog.IsDirty);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, TakeProfitOrder? TakeProfitOrder) ShowTakeProfitOrderCreateDialog(Window owner, Trade? preselectedTrade)
        {
            var dialog = new TakeProfitOrderCreateView(preselectedTrade)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, result ? dialog.TakeProfitOrder : null);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, bool IsDirty) ShowTakeProfitOrderEditDialog(Window owner, TakeProfitOrder takeProfitOrder)
        {
            var dialog = new TakeProfitOrderEditView(takeProfitOrder)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, dialog.IsDirty);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, Trade? Trade) ShowTradeCreateDialog(Window owner, ISymbolLookupService symbolLookupService,
                                                                      ITradingAccountLookupService tradingAccountLookupService, TradingAccount? preselectedTradingAccount)
        {
            var dialog = new TradeCreateView(symbolLookupService, tradingAccountLookupService, preselectedTradingAccount)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, result ? dialog.Trade : null);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, bool IsDirty) ShowTradeEditDialog(Window owner, Trade trade)
        {
            var dialog = new TradeEditView(trade)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, dialog.IsDirty);
        }

        /// <inheritdoc />
        public void ShowTradeDetailDialog(Window owner, Trade trade)
        {
            var dialog = new TradeDetailView(trade)
            {
                Owner = owner
            };

            dialog.ShowDialog();
        }

        /// <inheritdoc />
        public (bool IsConfirmed, TradeImage? TradeImage) ShowTradeImageCreateDialog(Window owner, Trade? preselectedTrade)
        {
            var dialog = new TradeImageCreateView(preselectedTrade)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, result ? dialog.TradeImage : null);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, bool IsDirty) ShowTradeImageEditDialog(Window owner, TradeImage tradeImage)
        {
            var dialog = new TradeImageEditView(tradeImage)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, dialog.IsDirty);
        }

        /// <inheritdoc />
        public void ShowTradeImageDetailDialog(Window owner, TradeImage tradeImage)
        {
            var dialog = new TradeImageDetailView(tradeImage)
            {
                Owner = owner
            };

            dialog.ShowDialog();
        }

        /// <inheritdoc />
        public (bool IsConfirmed, TradingAccount? TradingAccount) ShowTradingAccountCreateDialog(Window owner, IExchangeLookupService exchangeLookupService,
                                                                                                 Exchange? preselectedExchange)
        {
            var dialog = new TradingAccountCreateView(exchangeLookupService, preselectedExchange)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, result ? dialog.TradingAccount : null);
        }

        /// <inheritdoc />
        public (bool IsConfirmed, bool IsDirty) ShowTradingAccountEditDialog(Window owner, TradingAccount tradingAccount)
        {
            var dialog = new TradingAccountEditView(tradingAccount)
            {
                Owner = owner
            };

            var result = dialog.ShowDialog() == true;
            return (result, dialog.IsDirty);
        }

    }
}