using TD.AppInfra.Services;
using TD.Models;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.AppInfra.DesignTime
{
    /// <summary>
    /// Provides a no-op implementation of the ISymbolLookupService interface that returns an empty or
    /// mock list of symbols.
    /// </summary>
    /// <remarks>This implementation can be used in scenarios where symbol lookup functionality is optional or
    /// not required, such as in design time, in testing or when no ISymbolRepository are configured.</remarks>
    public partial class SymbolMockLookupService : ISymbolLookupService
    {
        public Task<IReadOnlyList<Symbol>> GetSymbolsAsync(bool isActive)
        {
            var symbols = new List<Symbol>();
            FillMockData(symbols);
            return Task.FromResult<IReadOnlyList<Symbol>>(symbols);
        }

        /// <summary>
        /// Populates the specified list with mock symbol data for testing or demonstration purposes.
        /// </summary>
        /// <remarks>This method is intended for use in test scenarios or when sample data is required.
        /// The implementation should ensure that the provided list is filled with representative symbol objects as
        /// needed by the caller.</remarks>
        /// <param name="symbols">The list of <see cref="Symbol"/> objects to populate with mock data. Must not be null.</param>
        partial void FillMockData(List<Symbol> symbols);
    }
}
