using System.Collections;
using System.ComponentModel;
using TD.Validation;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.AppInfra.ViewModels
{
    public abstract class AbstractDataErrorInfoVM : AbstractViewModel, INotifyDataErrorInfo
    {
        protected readonly Dictionary<string, List<string>> _errors = new Dictionary<string, List<string>>(StringComparer.Ordinal);
        public event EventHandler<DataErrorsChangedEventArgs>? ErrorsChanged;
        public bool HasErrors => _errors.Any(kvp => kvp.Value.Count > 0);

        public IEnumerable GetErrors(string? propertyName)
        {
            if (string.IsNullOrWhiteSpace(propertyName))
                return _errors.Values.SelectMany(x => x).Distinct().ToArray();

            if (!_errors.TryGetValue(propertyName, out var errors))
                return Enumerable.Empty<string>();

            return errors;
        }

        protected bool ValidateModel(object model)
        {
            var result = ModelValidator.Validate(model);
            ReplaceErrors(result);
            return !HasErrors;
        }

        protected bool ValidateProperty(object model, string propertyName)
        {
            var result = ModelValidator.ValidateProperty(model, propertyName);
            SetErrors(propertyName, result);
            return !_errors.ContainsKey(propertyName);
        }

        protected void AddError(string propertyName, string error)
        {
            if (!_errors.ContainsKey(propertyName))
                _errors[propertyName] = new List<string>();

            if (!_errors[propertyName].Contains(error))
            {
                _errors[propertyName].Add(error);
                OnErrorsChanged(propertyName);
            }
        }

        protected void ClearErrors(string propertyName)
        {
            if (_errors.Remove(propertyName))
                OnErrorsChanged(propertyName);
        }

        protected void ClearAllErrors()
        {
            var keys = _errors.Keys.ToArray();
            _errors.Clear();

            foreach (var key in keys)
                OnErrorsChanged(key);
        }

        protected void OnErrorsChanged(string propertyName)
        {
            ErrorsChanged?.Invoke(this, new DataErrorsChangedEventArgs(propertyName));
        }

        private void ReplaceErrors(IReadOnlyDictionary<string, IReadOnlyList<string>> source)
        {
            var currentKeys = _errors.Keys.ToArray();

            foreach (var key in currentKeys)
            {
                if (!source.ContainsKey(key))
                {
                    _errors.Remove(key);
                    OnErrorsChanged(key);
                }
            }

            foreach (var pair in source)
                SetErrors(pair.Key, pair.Value);
        }

        private void SetErrors(string propertyName, IEnumerable<string> errors)
        {
            var newErrors = errors.Where(x => !string.IsNullOrWhiteSpace(x)).Distinct().ToList();

            if (newErrors.Count == 0)
            {
                if (_errors.Remove(propertyName))
                    OnErrorsChanged(propertyName);

                return;
            }

            if (_errors.TryGetValue(propertyName, out var existing) && existing.SequenceEqual(newErrors))
                return;

            _errors[propertyName] = newErrors;
            OnErrorsChanged(propertyName);
        }
    }
}