using System.Collections.ObjectModel;
//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.AppInfra.ViewModels
{
    public abstract class AbstractCollectionVM<T> : AbstractViewModel where T : class
    {
        protected AbstractCollectionVM()
        {
            Collection = new ObservableCollection<T>();
            CollectionFiltered = Collection;
        }

        public ObservableCollection<T> Collection { get; }
        public ObservableCollection<T> CollectionFiltered { get; protected set; }

        protected virtual void OnSearchStringChanged() { }
        protected virtual void OnSelectedItemChanging(T? newSelectedItem) { }
        protected virtual void OnSelectedItemChanged(T? oldSelectedItem) { }

        public T? SelectedItem
        {
            get => _selectedItem;
            set
            {
                if (_selectedItem is IEquatable<T>)
                {
                    if (Equals(_selectedItem, value))
                        return;
                }
                OnSelectedItemChanging(value);
                var oldItem = _selectedItem;
                _selectedItem = value;
                RaisePropertyChanged(nameof(SelectedItem));
                OnSelectedItemChanged(oldItem);
            }
        }
        protected T? _selectedItem;

        public string SearchString
        {
            get => _searchString ?? string.Empty;
            set
            {
                _searchString = value;
                RaisePropertyChanged(nameof(SearchString));
                OnSearchStringChanged();
                if (SelectedItem == null)
                {
                    if (CollectionFiltered.Count > 0)
                        SelectedItem = CollectionFiltered[0];
                }
                RaisePropertyChanged(nameof(CollectionFiltered));
            }
        }
        private string? _searchString;

        protected void ReplaceCollection<K>(ObservableCollection<K> target, IEnumerable<K> source)
        {
            target.Clear();
            foreach (var item in source)
            {
                target.Add(item);
            }
        }
    }
}