using TD.i18n;

//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
namespace TD.Helpers
{
    /// <summary>
    /// Represents the query parameters for pagination and searching.
    /// </summary>
    public partial class QueryParameters
    {
        public QueryParameters()
        {
            Page = 1;
            PageSize = 20;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="QueryParameters"/> class based on the specified query parameters.
        /// </summary>
        /// <param name="queryParameters">The query parameters to copy values from.</param>
        public QueryParameters(QueryParameters queryParameters)
        {
            if (queryParameters != null)
            {
                Page = queryParameters.Page;
                PageSize = queryParameters.PageSize;
                SearchString = queryParameters.SearchString;
            }
        }

        /// <summary>
        /// Gets a value indicating whether there is a next page available.
        /// </summary>
        public bool HasNextPage => Page < PageCount;

        /// <summary>
        /// Gets a value indicating whether there is a previous page available.
        /// </summary>
        public bool HasPrevPage => Page > 1;

        /// <summary>
        /// Gets or sets the current page number.
        /// </summary>
        public int Page { get; set; }

        /// <summary>
        /// Gets or sets the number of items per page.
        /// </summary>
        public int PageSize { get; set; }

        /// <summary>
        /// Gets or sets the general purpose search string.
        /// </summary>
        public string? SearchString { get; set; }

        /// <summary>
        /// Gets the total number of pages based on the total count and page size.
        /// </summary>
        public int PageCount
        {
            get
            {
                return TotalCount > 0 ? (int)Math.Ceiling(TotalCount / (double)PageSize) : 0;
            }
        }

        /// <summary>
        /// Gets a localized string displaying pagination information including current page, total pages.
        /// </summary>
        public string PageInfo
        {
            get
            {
                if (TotalCount == 0)
                    return $"{CommonStrings.Page} 0 / 0 ";

                return $"{CommonStrings.Page} {Page} / {PageCount}";
            }
        }

        /// <summary>       
        /// Gets a localized string displaying the total number of records.
        /// </summary>
        public string RecordsInfo
        {
            get
            {
                if (TotalCount == 0)
                    return MessageStrings.NoResults;

                return $"{CommonStrings.TotalRecords}: {TotalCount}";
            }
        }

        /// <summary>
        /// Gets the number of items to skip based on the current page and page size.
        /// </summary>
        public int Skip
        {
            get { return (Page - 1) * PageSize; }
        }

        /// <summary>
        /// Gets or sets the total number of records that match the query criteria.
        /// </summary>
        public long TotalCount
        {
            get { return _totalCount; }
            set
            {
                _totalCount = value;
                if (Page < 1) Page = 1;
                if (Page > PageCount) Page = PageCount;
                long skip = (Page - 1) * PageSize;
            }
        }
        long _totalCount;

        public virtual bool HasAnySearchCriteria()
        {
            _hasAnySearchCriteria = !string.IsNullOrEmpty(SearchString);

            OnHasAnySearchCriteria();
            return _hasAnySearchCriteria;
        }

        /// <summary>
        /// Called when determining if there are any search criteria, can be used in a partial class to extend the logic.
        /// Setting _hasAnySearchCriteria to true in this method will indicate that there are search criteria.
        /// </summary>
        partial void OnHasAnySearchCriteria();
        bool _hasAnySearchCriteria;
    }
}
