//----------------------------------------------------------------------------------
//
//     This code file was generated by OzzCodeGen.
//
//     Manual changes to this file will be overwritten if the code is regenerated,
//     so manual changes should be made in another partial class file.
//
//----------------------------------------------------------------------------------
using System.Globalization;
using Microsoft.Data.Sqlite;

namespace TD.SQLite.Extensions
{
    /// <summary>
    /// Extension methods for <see cref="SqliteCommand"/> to simplify adding parameters, especially nullable ones.
    /// </summary>
    public static class SqliteExtensions
    {
        /// <summary>
        /// Adds a non-nullable DateTime parameter as a text representation to the specified <see cref="SqliteCommand"/>.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Must not be null or empty.</param>
        /// <param name="value">The DateTime value to convert and assign.</param>
        public static void AddDateTimeToTextParameter(this SqliteCommand command, string parameterName, DateTime value)
        {
            var parameter = command.GetParameter(parameterName, SqliteType.Text);
            parameter.Value = value.ToUniversalTime().ToString("O");
            command.Parameters.Add(parameter);
        }

        /// <summary>
        /// Adds a nullable DateTime parameter as a text representation to the specified <see cref="SqliteCommand"/>.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Must not be null or empty.</param>
        /// <param name="value">The nullable DateTime value to convert and assign. If null, the parameter value is set to null.</param>
        public static void AddDateTimeToTextParameter(this SqliteCommand command, string parameterName, DateTime? value)
        {
            if (value.HasValue)
            {
                command.AddDateTimeToTextParameter(parameterName, value.Value);
            }
            else
            {
                command.AddNullParameter(parameterName);
            }
        }

        /// <summary>
        /// Adds a nullable decimal parameter as a scaled integer (<see cref="SqliteType.Integer"/>) to the specified
        /// <see cref="SqliteCommand"/>.
        /// </summary>
        /// <remarks>
        /// The decimal value is multiplied by 10 raised to <paramref name="scale"/> before being assigned to the
        /// parameter. For example, with scale 4, 123.66 is stored as 1236600. Values less than 1 are treated as 1.
        /// </remarks>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added.</param>
        /// <param name="parameterName">The name of the parameter to add.</param>
        /// <param name="value">The nullable decimal value to convert and assign. If null, the parameter value is set to null.</param>
        /// <param name="scale">The base-10 scale used for decimal-to-integer conversion.</param>
        public static void AddDecimalToIntegerParameter(this SqliteCommand command, string parameterName, decimal? value, int scale)
        {
            if (scale < 1)
                throw new ArgumentOutOfRangeException(nameof(scale), scale, "Scale must be greater than or equal to 1.");

            if (value.HasValue)
            {
                command.AddDecimalToIntegerParameter(parameterName, value.Value, scale);
            }
            else
            {
                command.AddNullParameter(parameterName);
            }
        }

        /// <summary>
        /// Adds a parameter to the specified <see cref="SqliteCommand"/> by converting the given decimal value to an
        /// integer representation using the specified scale.
        /// </summary>
        /// <remarks>This method is typically used to store decimal values as scaled integers in SQLite
        /// databases, preserving precision by multiplying the value by 10 raised to the specified scale.</remarks>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Cannot be null or empty.</param>
        /// <param name="value">The decimal value to convert and add as a parameter.</param>
        /// <param name="scale">The number of decimal places to use when scaling the value for integer storage. Must be zero or greater.</param>
        public static void AddDecimalToIntegerParameter(this SqliteCommand command, string parameterName, decimal value, int scale)
        {
            if (scale < 1)
                throw new ArgumentOutOfRangeException(nameof(scale), scale, "Scale must be greater than or equal to 1.");

            var parameter = command.GetParameter(parameterName, SqliteType.Integer);
            parameter.Value = (long)(value * (long)Math.Pow(10, scale));
            command.Parameters.Add(parameter);
        }

        /// <summary>
        /// Adds a nullable decimal as a text parameter to the specified <see cref="SqliteCommand"/>. If the value is null, the
        /// parameter is set to <see langword="DBNull.Value"/>; otherwise, the decimal value is assigned.
        /// </summary>
        /// <remarks>The decimal value is added as a text parameter to preserve precision when storing in SQLite.</remarks>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added.</param>
        /// <param name="parameterName">The name of the parameter to add to the command.</param>
        /// <param name="value">The nullable decimal value to assign to the parameter. If null, the parameter is set to <see
        /// langword="DBNull.Value"/>.</param>
        public static void AddDecimalToTextParameter(this SqliteCommand command, string parameterName, decimal? value)
        {
            if (value.HasValue)
            {
                command.AddParameter(parameterName, value.Value.ToString(CultureInfo.InvariantCulture));
            }
            else
            {
                command.AddNullParameter(parameterName);
            }
        }

        /// <summary>
        /// Adds a decimal value as a text parameter to the specified SqliteCommand.
        /// </summary>
        /// <remarks>The decimal value is added as a text parameter to preserve precision when storing in
        /// SQLite. This method is a convenience overload for non-nullable decimal values.</remarks>
        /// <param name="command">The SqliteCommand to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Must not be null or empty.</param>
        /// <param name="value">The decimal value to assign to the parameter.</param>
        public static void AddDecimalToTextParameter(this SqliteCommand command, string parameterName, decimal value)
        {
            AddDecimalToTextParameter(command, parameterName, (decimal?)value);
        }

        /// <summary>
        /// Adds a nullable double parameter to the specified <see cref="SqliteCommand"/> as a parameter of type <see
        /// cref="SqliteType.Real"/>. If the value is null, the parameter is set to <see cref="DBNull.Value"/>.
        /// </summary>
        /// <remarks>This extension method simplifies adding parameters that may have null values to a
        /// SQLite command, ensuring correct handling of database nulls.</remarks>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Cannot be null or empty.</param>
        /// <param name="value">The nullable double value to assign to the parameter. If null, the parameter value is set to <see
        /// cref="DBNull.Value"/>.</param>
        public static void AddNullableParameter(this SqliteCommand command, string parameterName, double? value)
        {
            var parameter = command.GetParameter(parameterName, SqliteType.Real);
            parameter.Value = value is null ? DBNull.Value : value;
            command.Parameters.Add(parameter);
        }

        /// <summary>
        /// Adds a nullable text parameter to the specified <see cref="SqliteCommand"/>. If the value is null, the
        /// parameter is set to <see cref="DBNull.Value"/>; otherwise, it is set to the provided string value.
        /// </summary>
        /// <remarks>This method simplifies adding parameters that may have null values, ensuring correct
        /// handling of database NULLs in SQLite commands.</remarks>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Must not be null or empty.</param>
        /// <param name="value">The string value to assign to the parameter, or null to represent a database NULL.</param>
        public static void AddNullableParameter(this SqliteCommand command, string parameterName, string? value)
        {
            if (string.IsNullOrEmpty(value))
            {
                command.AddNullParameter(parameterName);
            }
            else
            {
                command.AddParameter(parameterName, value);
            }
        }

        /// <summary>
        /// Adds a non-nullable boolean parameter to the specified <see cref="SqliteCommand"/>.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Cannot be null or empty.</param>
        /// <param name="value">The boolean value to assign to the parameter.</param>
        public static void AddParameter(this SqliteCommand command, string parameterName, bool value)
        {
            AddParameter(command, parameterName, (long)(value ? 1 : 0));
        }

        /// <summary>
        /// Adds a nullable boolean parameter to the specified <see cref="SqliteCommand"/>. If the value is null, the parameter is set to <see cref="DBNull.Value"/>.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Cannot be null or empty.</param>
        /// <param name="value">The nullable boolean value to assign to the parameter. If null, the parameter value is set to <see cref="DBNull.Value"/>.</param>
        public static void AddParameter(this SqliteCommand command, string parameterName, bool? value)
        {
            if (value.HasValue)
            {
                command.AddParameter(parameterName, value.Value);
            }
            else
            {
                command.AddNullParameter(parameterName);
            }
        }

        /// <summary>
        /// Adds a non-nullable 64-bit integer parameter to the specified <see cref="SqliteCommand"/>.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Cannot be null or empty.</param>
        /// <param name="value">The 64-bit integer value to assign to the parameter.</param>
        public static void AddParameter(this SqliteCommand command, string parameterName, long value)
        {
            var parameter = command.GetParameter(parameterName, SqliteType.Integer);
            parameter.Value = value;
            command.Parameters.Add(parameter);
        }


        /// <summary>
        /// Adds a nullable 64-bit integer parameter to the specified <see cref="SqliteCommand"/>.
        /// </summary>
        /// <remarks>This method simplifies adding parameters that may have null values to a SQLite
        /// command, ensuring that nulls are correctly represented as <see cref="DBNull.Value"/> in the
        /// database.</remarks>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Cannot be null or empty.</param>
        /// <param name="value">The nullable 64-bit integer value to assign to the parameter. If null, the parameter value is set to <see
        /// cref="DBNull.Value"/>.</param>
        public static void AddParameter(this SqliteCommand command, string parameterName, long? value)
        {
            if (value.HasValue)
            {
                command.AddParameter(parameterName, value.Value);
            }
            else
            {
                command.AddNullParameter(parameterName);
            }
        }

        /// <summary>
        /// Adds a non-nullable integer parameter to the specified <see cref="SqliteCommand"/>. The parameter value is set to the provided integer value.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added.</param>
        /// <param name="parameterName">The name of the parameter to add. Cannot be null or empty.</param>
        /// <param name="value">The integer value to assign to the parameter.</param>
        public static void AddParameter(this SqliteCommand command, string parameterName, int value)
        {
            AddParameter(command, parameterName, (long)value);
        }

        /// <summary>
        /// Adds a nullable integer parameter to the specified <see cref="SqliteCommand"/>. If the value is null, the
        /// parameter is set to <see langword="DBNull.Value"/>; otherwise, the integer value is assigned.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added.</param>
        /// <param name="parameterName">The name of the parameter to add to the command.</param>
        /// <param name="value">The nullable integer value to assign to the parameter. If null, the parameter is set to <see
        /// langword="DBNull.Value"/>.</param>
        public static void AddParameter(this SqliteCommand command, string parameterName, int? value)
        {
            AddParameter(command, parameterName, (long?)value);
        }

        /// <summary>
        /// Adds a parameter with a null value to the specified <see cref="SqliteCommand"/>.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Must not be null or empty.</param>
        public static void AddNullParameter(this SqliteCommand command, string parameterName)
        {
            var parameter = command.GetParameter(parameterName, SqliteType.Text);
            parameter.Value = DBNull.Value;
            command.Parameters.Add(parameter);
        }

        /// <summary>
        /// Adds a non-nullable text parameter to the specified <see cref="SqliteCommand"/>. The parameter value is set to the provided string value.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added. Cannot be null.</param>
        /// <param name="parameterName">The name of the parameter to add. Must not be null or empty.</param>
        /// <param name="value">The string value to assign to the parameter.</param>
        public static void AddParameter(this SqliteCommand command, string parameterName, string value)
        {
            var parameter = command.GetParameter(parameterName, SqliteType.Text);
            parameter.Value = value;
            command.Parameters.Add(parameter);
        }

        /// <summary>
        /// Converts a scaled integer value from the specified column in the data reader to a nullable decimal.
        /// </summary>
        /// <remarks>Use this method to read decimal values that are stored as scaled integers in the
        /// database. The method divides the integer value by 10 raised to the specified scale to obtain the original
        /// decimal value.</remarks>
        /// <param name="reader">The SqliteDataReader instance from which to retrieve the value.</param>
        /// <param name="ordinal">The zero-based column ordinal of the value to convert.</param>
        /// <param name="scale">The number of decimal places by which the integer value is scaled.</param>
        /// <returns>A nullable decimal representing the unscaled value from the specified column, or null if the column is
        /// DBNull.</returns>
        public static decimal? GetDecimalFromInteger(this SqliteDataReader reader, int ordinal, int scale)
        {
            if (reader.IsDBNull(ordinal))
            {
                return null;
            }
            var value = reader.GetInt64(ordinal);
            return value / (decimal)Math.Pow(10, scale);
        }

        /// <summary>
        /// Retrieves a nullable decimal value from the specified <see cref="SqliteDataReader"/> at the given ordinal.
        /// </summary>
        /// <param name="reader">The <see cref="SqliteDataReader"/> from which to retrieve the value.</param>
        /// <param name="ordinal">The zero-based column ordinal.</param>
        /// <returns>The nullable decimal value, or null if the column is DBNull.</returns>
        public static decimal? GetDecimalFromText(this SqliteDataReader reader, int ordinal)
        {
            if (reader.IsDBNull(ordinal))
            {
                return null;
            }
            var value = reader.GetString(ordinal);
            if (decimal.TryParse(value, NumberStyles.Any, CultureInfo.InvariantCulture, out decimal result))
            {
                return result;
            }
            throw new FormatException($"The value '{value}' at ordinal {ordinal} cannot be parsed as a decimal.");
        }

        /// <summary>
        /// Creates a new <see cref="SqliteParameter"/> with the specified name and type for the given <see
        /// cref="SqliteCommand"/>.
        /// </summary>
        /// <param name="command">The <see cref="SqliteCommand"/> to which the parameter will be added.</param>
        /// <param name="parameterName">The name to assign to the parameter.</param>
        /// <param name="paramType">The SQLite data type to assign to the parameter.</param>
        /// <returns>A new <see cref="SqliteParameter"/> instance with the specified name and type.</returns>
        public static SqliteParameter GetParameter(this SqliteCommand command, string parameterName, SqliteType paramType)
        {
            var parameter = command.CreateParameter();
            parameter.ParameterName = parameterName;
            parameter.SqliteType = paramType;

            return parameter;
        }
    }
}
